import {
  buildFlashcards,
  combineFlashcardLibraries,
  defineFlashcardLibrary,
} from "./flashcard-schema";
import { foundationExpansionLibrary } from "./flashcard-library/foundations";
import { modelFoundationsExpansionLibrary } from "./flashcard-library/model-foundations";
import { systemsAndProductExpansionLibrary } from "./flashcard-library/systems-and-product";

export { flashcardSubjects } from "./flashcard-schema";
export type {
  Flashcard,
  FlashcardSubject,
  FlashcardSubjectId,
} from "./flashcard-schema";

const coreFlashcardLibrary = defineFlashcardLibrary({
  "Rank and shape": {
    subjectId: "linear-algebra",
    module: "Linear Algebra Basics",
    lesson: "Arrays and Shapes",
    definition: "Rank is the number of axes in an array; shape gives the length of each axis in order.",
    details: [
      "A scalar has rank 0, a vector rank 1, and a matrix rank 2.",
      "The product of the shape dimensions is the total number of stored values.",
      "Code and data conventions give each axis its meaning, such as batch, token, or feature.",
    ],
    example: "A matrix with shape (2, 3) has two rows, three columns, and six values.",
  },
  "Reshape invariants": {
    subjectId: "linear-algebra",
    module: "Linear Algebra Basics",
    lesson: "Arrays and Shapes",
    definition: "Reshaping changes how values are arranged without changing the values or their total count.",
    details: [
      "The new dimensions must multiply to the original array size.",
      "Reshape preserves the value order; it does not perform a numerical transformation.",
      "A new shape may give the axes new meaning, so that meaning should be stated explicitly.",
    ],
    example: "Six values can reshape from (6,) to (2, 3), but not to (4, 2).",
  },
  "Vector operations": {
    subjectId: "linear-algebra",
    module: "Linear Algebra Basics",
    lesson: "Vector Operations",
    definition: "Vector addition and scaling operate on coordinates in their fixed order.",
    details: [
      "Matching positions must represent the same feature.",
      "Addition requires equal shapes and adds matching coordinates.",
      "Scalar multiplication multiplies every coordinate by the same number.",
    ],
    example: "[1, 2] + [3, 4] = [4, 6], while 3 × [1, -2] = [3, -6].",
  },
  "L2 norm": {
    subjectId: "linear-algebra",
    module: "Linear Algebra Basics",
    lesson: "Vector Operations",
    definition: "The L2 norm measures vector length as the square root of the sum of squared coordinates.",
    details: [
      "The norm is always non-negative and is zero only for the zero vector.",
      "Scaling a vector by k scales its length by |k|.",
      "The calculation combines every coordinate into one number.",
    ],
    example: "The L2 norm of [3, 4] is sqrt(3² + 4²) = 5.",
  },
  "Dot product": {
    subjectId: "linear-algebra",
    module: "Linear Algebra Basics",
    lesson: "Dot Products",
    definition: "A dot product multiplies matching coordinates and adds them to produce one scalar.",
    details: [
      "The vectors must have the same length.",
      "For nonzero real vectors, positive, zero, and negative dot products correspond to acute, right, and obtuse angles.",
      "Vector magnitude affects the result as well as direction.",
    ],
    example: "[1, 2] · [3, 4] = 1×3 + 2×4 = 11.",
  },
  "Cosine similarity": {
    subjectId: "linear-algebra",
    module: "Linear Algebra Basics",
    lesson: "Dot Products",
    definition: "Cosine similarity divides a dot product by both vector lengths to compare direction rather than scale.",
    details: [
      "Its range is -1 to 1 for nonzero vectors.",
      "Values near 1, 0, and -1 mean similar, perpendicular, and opposite directions.",
      "It is undefined when either vector has zero length.",
    ],
    example: "The cosine similarity of [1, 0] and [0, 1] is 0 because they are perpendicular.",
  },
  "Matrix-vector multiplication": {
    subjectId: "linear-algebra",
    module: "Linear Algebra Basics",
    lesson: "Matrix Multiplication",
    definition: "A matrix-vector product takes one dot product between the input vector and each matrix row.",
    details: [
      "The matrix column count must equal the vector length.",
      "Each matrix row creates one output coordinate.",
      "A rectangular matrix can change the feature width.",
    ],
    example: "A (3, 2) matrix times a (2,) vector produces a (3,) vector.",
  },
  "Linear layer": {
    subjectId: "linear-algebra",
    module: "Linear Algebra Basics",
    lesson: "Matrix Multiplication",
    definition: "Libraries often call W x + b a linear layer, although a nonzero bias makes the complete map affine.",
    details: [
      "Each row of W belongs to one output coordinate, and the bias length must match the output width.",
      "Setting b to zero leaves the strictly linear map W x.",
      "Attention and vocabulary projections commonly use W x; whether they include a bias depends on the model.",
    ],
    example: "If W has shape (3, 2), x shape (2,), and b shape (3,), the output has shape (3,).",
  },
  "Batched linear layer": {
    subjectId: "linear-algebra",
    module: "Linear Algebra Basics",
    lesson: "Batches and Broadcasting",
    definition: "A batched linear layer applies the same learned weights to every input row at once.",
    details: [
      "Inputs use shape (batch, input width).",
      "Weights use shape (output width, input width).",
      "X @ Wᵀ keeps the batch size and changes the feature width.",
    ],
    example: "Inputs (5, 4) and weights (3, 4) produce outputs with shape (5, 3).",
  },
  Broadcasting: {
    subjectId: "linear-algebra",
    module: "Linear Algebra Basics",
    lesson: "Batches and Broadcasting",
    definition: "Broadcasting reuses a smaller compatible array across a larger array without manually copying it.",
    details: [
      "Dimensions align from the end and must match or have size 1.",
      "A one-row bias can be added to every row in a batch.",
      "The repeated values are shared by rule, not learned separately for each example.",
    ],
    example: "Adding bias shape (3,) to activations shape (5, 3) adds the same three values to all five rows.",
  },
  "Features and targets": {
    subjectId: "machine-learning-basics",
    module: "Machine Learning Basics",
    lesson: "Training and Validation Data",
    definition: "Features are the inputs used to make a prediction; the target is the answer the model should predict.",
    details: [
      "One row is one example.",
      "For n examples with d features and one scalar target each, X has shape (n, d) and y has shape (n,).",
      "In a language model, prefix tokens are inputs and the next token is the target.",
    ],
    example: "A row [temperature, humidity] → rain label contains two features and one target.",
  },
  "Training-validation split": {
    subjectId: "machine-learning-basics",
    module: "Machine Learning Basics",
    lesson: "Training and Validation Data",
    definition: "Training data updates parameters; validation data stays held out to measure performance on unseen examples.",
    details: [
      "The two sets must be disjoint.",
      "Validation data may guide model selection, but it must not drive parameter updates; repeated tuning against the same data can overfit it.",
      "Overlap creates data leakage and makes evaluation look better than it is.",
    ],
    example: "With eight rows, six may train the model while two untouched rows measure it.",
  },
  "Linear prediction": {
    subjectId: "machine-learning-basics",
    module: "Machine Learning Basics",
    lesson: "Linear Regression",
    definition: "Linear regression predicts a number with y_hat = x · w + b.",
    details: [
      "Each weight says how one feature changes the prediction.",
      "The bias shifts every prediction by the same amount.",
      "Training changes weights and bias, not the observed features or targets.",
    ],
    example: "For x = [2, -1], w = [3, 4], and b = 0.5, the prediction is 2.5.",
  },
  "Mean squared error": {
    subjectId: "machine-learning-basics",
    module: "Machine Learning Basics",
    lesson: "Linear Regression",
    definition: "Mean squared error averages (prediction - target)² across examples.",
    details: [
      "Squaring keeps positive and negative residuals from cancelling.",
      "Large misses count more heavily than small misses.",
      "A perfect set of predictions has MSE 0.",
    ],
    example: "Residuals [1, -2] give MSE (1² + (-2)²) / 2 = 2.5.",
  },
  Gradient: {
    subjectId: "machine-learning-basics",
    module: "Machine Learning Basics",
    lesson: "Gradient Descent",
    definition: "A gradient reports the local slope of the loss with respect to each parameter.",
    details: [
      "A positive component means increasing that parameter raises nearby loss.",
      "A negative component means increasing that parameter lowers nearby loss.",
      "The gradient is local, so its guidance can change after an update.",
    ],
    example: "If dL/dw = -2, a small increase in w is expected to lower the loss nearby.",
  },
  "Gradient descent update": {
    subjectId: "machine-learning-basics",
    module: "Machine Learning Basics",
    lesson: "Gradient Descent",
    definition: "Gradient descent updates each parameter with parameter = parameter - learning_rate × gradient.",
    details: [
      "The minus sign moves against the local direction of increasing loss.",
      "A tiny learning rate moves slowly; a large one can overshoot.",
      "Training repeats prediction, loss, gradient, and update steps.",
    ],
    example: "With w = 1, gradient -2, and learning rate 0.1, the new w is 1.2.",
  },
  "Logit and sigmoid": {
    subjectId: "machine-learning-basics",
    module: "Machine Learning Basics",
    lesson: "Binary Classification",
    definition: "A logit is an unrestricted model score; sigmoid maps it to a probability between 0 and 1.",
    details: [
      "A zero logit maps to 0.5.",
      "Positive logits map above 0.5 and negative logits below it.",
      "Stable implementations avoid exponent overflow for extreme scores.",
    ],
    example: "sigmoid(2) is about 0.881, while sigmoid(-2) is about 0.119.",
  },
  "Binary cross-entropy": {
    subjectId: "machine-learning-basics",
    module: "Machine Learning Basics",
    lesson: "Binary Classification",
    definition: "Binary cross-entropy scores the probability assigned to a zero-or-one target.",
    details: [
      "For target 1, loss is -log(p); for target 0, it is -log(1 - p).",
      "A confident correct prediction has low loss; a confident wrong one has high loss.",
      "Clipping boundary probabilities avoids log(0).",
    ],
    example: "For y = 1 and p = 0.881, the loss is -log(0.881) ≈ 0.127.",
  },
  "Dense layer": {
    subjectId: "machine-learning-basics",
    module: "Machine Learning Basics",
    lesson: "Neural Networks",
    definition: "A dense layer computes W x + b so every output can combine every input feature.",
    details: [
      "Each output unit owns one weight row and one bias.",
      "The raw result before activation is called the pre-activation.",
      "Dense layers can map one feature width to another.",
    ],
    example: "A weight matrix with two rows turns one input vector into two pre-activation values.",
  },
  "ReLU nonlinearity": {
    subjectId: "machine-learning-basics",
    module: "Machine Learning Basics",
    lesson: "Neural Networks",
    definition: "ReLU applies max(0, z) to each coordinate, keeping positive values and replacing negative ones with zero.",
    details: [
      "ReLU changes values without changing shape.",
      "Without a nonlinearity, stacked affine layers collapse into one affine map.",
      "Dense → activation → dense is also the basic pattern of a Transformer feed-forward block.",
    ],
    example: "ReLU([-2, 0.5, 3]) = [0, 0.5, 3].",
  },
  "Recurrent hidden state": {
    subjectId: "model-foundations",
    module: "Model Foundations",
    lesson: "Character RNNs",
    definition: "A recurrent neural network (RNN) carries prefix information by updating a hidden state with the current input and previous state.",
    details: [
      "The same transition weights are reused at every sequence position.",
      "h_t = tanh(Wxh x_t + Whh h_(t-1) + b).",
      "A projection turns h_t into next-character logits.",
    ],
    example: "After reading “th,” the state can carry information about “t” while the current one-hot input identifies “h.”",
  },
  "Teacher forcing and generation": {
    subjectId: "model-foundations",
    module: "Model Foundations",
    lesson: "Character RNNs",
    definition: "Teacher forcing uses the real next character as the next training input; generation feeds back the model's sampled character.",
    details: [
      "Cross-entropy is -log p(target), so low target probability costs more.",
      "Backpropagation through time sends loss through the unrolled recurrent steps.",
      "Truncation limits the window, and gradient clipping limits gradient size before an optimizer step.",
    ],
    example: "Training on “cat” feeds the real “a” after “c,” even if the model guessed another character.",
  },
  "Learned embeddings": {
    subjectId: "model-foundations",
    module: "Model Foundations",
    lesson: "Neural Language Models",
    definition: "An embedding table maps each token id to a learned continuous vector.",
    details: [
      "Looking up an id selects one trainable table row.",
      "A context representation can combine several token embeddings, such as by averaging.",
      "Tokens with similar predictive roles may become nearby when that helps the training objective; proximity is learned, not guaranteed semantic relatedness.",
    ],
    example: "Two context ids select two rows, whose coordinate-wise mean becomes one context vector.",
  },
  "Softmax, NLL, and perplexity": {
    subjectId: "model-foundations",
    module: "Model Foundations",
    lesson: "Neural Language Models",
    definition: "Softmax normalizes vocabulary logits, negative log-likelihood scores the target, and perplexity is exp(average loss).",
    details: [
      "Subtracting the largest logit before exponentiating prevents overflow without changing probabilities.",
      "NLL reads -log p(target), not the probability of whichever token ranked first.",
      "Scoring every vocabulary item makes a large output vocabulary expensive.",
    ],
    example: "An average loss of 2.53 gives perplexity exp(2.53) ≈ 12.6.",
  },
  "BPE training": {
    subjectId: "model-foundations",
    module: "Model Foundations",
    lesson: "Subword Tokenization",
    definition: "Byte-pair encoding repeatedly merges the most common adjacent symbol pair in its training corpus.",
    details: [
      "Training starts from base symbols and counts neighboring pairs.",
      "Each round replaces non-overlapping matches, then recounts because new pairs now exist.",
      "More merges usually shorten sequences while enlarging the vocabulary.",
    ],
    example: "If [s, i] is most frequent, BPE merges it to si everywhere, then counts pairs again.",
  },
  "Ordered BPE encoding": {
    subjectId: "model-foundations",
    module: "Model Foundations",
    lesson: "Subword Tokenization",
    definition: "A trained BPE tokenizer is an ordered merge list that must be replayed in the same order on new text.",
    details: [
      "A later merge may depend on a symbol created by an earlier one.",
      "Pair identities must stay distinct; [a, bc] is not [ab, c].",
      "The merge table is part of the model contract because it fixes token ids and sequence lengths.",
    ],
    example: "For abc, [a,b] must run before [ab,c] to produce the single token abc.",
  },
  "Additive attention score": {
    subjectId: "model-foundations",
    module: "Model Foundations",
    lesson: "Additive Attention",
    definition: "Additive attention scores one decoder query against every encoder state with a small learned network.",
    details: [
      "The score is e_(t,i) = vᵀ tanh(Wq q_t + Wk h_i + b).",
      "Wq and Wk project query and key into the same attention width.",
      "A new query at each output step produces a new row of scores.",
    ],
    example: "A query for the output year can give the source state “2026” a much higher score than day or month.",
  },
  "Attention context vector": {
    subjectId: "model-foundations",
    module: "Model Foundations",
    lesson: "Additive Attention",
    definition: "Softmax turns position scores into weights, and their weighted sum creates a query-specific context vector.",
    details: [
      "Softmax runs across source positions for one query.",
      "The weights are positive and add up to 1.",
      "c_t = Σ_i alpha_(t,i) h_i has the same width as an encoder state.",
    ],
    example: "Weights [.014, .035, .951] make the context mostly the third encoder state.",
  },
  "Scaled dot-product attention": {
    subjectId: "model-foundations",
    module: "Model Foundations",
    lesson: "Transformers",
    definition: "Scaled dot-product attention compares queries with keys, normalizes the scores, and mixes values.",
    details: [
      "QKᵀ creates one score for every query-key position pair.",
      "Dividing by sqrt(d_k) keeps wide dot products from saturating softmax.",
      "The normalized n × n weights multiply V to produce context rows.",
    ],
    example: "For three tokens, QKᵀ has shape (3, 3), and multiplying its probabilities by V returns three context vectors.",
  },
  "Causal masking": {
    subjectId: "model-foundations",
    module: "Model Foundations",
    lesson: "Transformers",
    definition: "A causal mask prevents a token position from attending to later positions.",
    details: [
      "Future scores j > i become -Infinity before softmax.",
      "Those positions receive exactly zero probability after normalization.",
      "The remaining weights still sum to 1, allowing parallel training without future leakage.",
    ],
    example: "At position 2, positions 1 and 2 may be visible, while position 3 is masked out.",
  },
  "Frozen-weight adaptation": {
    subjectId: "model-foundations",
    module: "Model Foundations",
    lesson: "In-Context Learning",
    definition: "In-context learning changes predictions through prompt-conditioned activations without updating model weights.",
    details: [
      "Instruction, examples, and query form one causal token sequence.",
      "The prompt changes hidden activations and the KV cache.",
      "No optimizer or gradient-descent step runs during normal inference.",
    ],
    example: "Adding labeled examples can teach an output format for this request while every learned parameter stays fixed.",
  },
  "Zero-, one-, and few-shot evaluation": {
    subjectId: "model-foundations",
    module: "Model Foundations",
    lesson: "In-Context Learning",
    definition: "Zero-shot supplies no worked demonstrations, one-shot supplies one, and few-shot supplies several within the prompt.",
    details: [
      "A zero-shot prompt may still contain task instructions and the query to answer.",
      "Keep queries, decoding settings, label extraction, and scoring fixed.",
      "Choosing prompts after test results leaks test information, and tiny local studies do not establish general gains.",
    ],
    example: "Compare the same held-out reviews with 0, 1, and 4 demonstrations using exact-match scoring.",
  },
  "Prefill and decode": {
    subjectId: "inference-runtime",
    module: "Inference Runtime",
    lesson: "Inference Runtime",
    definition: "Prefill processes the prompt in parallel; decode then advances generation one position at a time.",
    details: [
      "Prefill saves prompt keys and values and supplies logits for the first output token.",
      "Generating N tokens needs max(0, N - 1) later decode forwards.",
      "Final sequence length is prompt tokens plus every generated token.",
    ],
    example: "A 96-token prompt and 32-token output use one prefill and 31 decode forwards.",
  },
  "KV-cache accounting": {
    subjectId: "inference-runtime",
    module: "Inference Runtime",
    lesson: "Inference Runtime",
    definition: "The KV cache stores one key and one value per cached sequence position at each cached-attention layer.",
    details: [
      "Bytes = 2 × layers × KV heads × tokens × head dimension × bytes per value.",
      "Grouped-query attention uses the KV-head count here, not the query-head count.",
      "TTFT includes queueing and prefill, while ITL measures gaps between later visible tokens.",
    ],
    example: "Doubling the cached token count doubles one request's KV-cache memory.",
  },
  "Continuous batching": {
    subjectId: "inference-runtime",
    module: "Inference Runtime",
    lesson: "Scheduling and Memory",
    definition: "Continuous batching can remove finished requests and admit waiting ones between decode iterations.",
    details: [
      "Each active sequence advances by at most one token per iteration.",
      "Finished work releases its KV pages before the next admission decision.",
      "Throughput gains depend on workload, fairness, prefill interference, and scheduling overhead.",
    ],
    example: "When request A finishes, request D can take its slot for the next decode round instead of waiting for the whole batch.",
  },
  "Paged KV cache": {
    subjectId: "inference-runtime",
    module: "Inference Runtime",
    lesson: "Scheduling and Memory",
    definition: "Paged KV allocation grows a request in fixed-size blocks instead of reserving one large contiguous region.",
    details: [
      "Page count is ceiling(tokens / page size).",
      "Unused capacity is always less than one page per request.",
      "Pages can be returned and reused when a sequence finishes.",
    ],
    example: "At page size 16, 33 cached positions need 3 pages: capacity 48 with 15 unused slots.",
  },
  "Streaming UTF-8 decoding": {
    subjectId: "llm-serving",
    module: "LLM Serving",
    lesson: "Streaming Transport",
    definition: "Network chunks must pass through a streaming UTF-8 decoder before text frames are parsed.",
    details: [
      "A Uint8Array chunk can stop in the middle of a multi-byte character.",
      "TextDecoder with stream enabled carries incomplete bytes into the next chunk.",
      "Chunk boundaries do not imply character, JSON, event, or token boundaries.",
    ],
    example: "The three UTF-8 bytes for € may arrive in two chunks but still decode to one character.",
  },
  "SSE framing and typed events": {
    subjectId: "llm-serving",
    module: "LLM Serving",
    lesson: "Streaming Transport",
    definition: "An SSE parser keeps unfinished text until a blank line completes a frame, then maps wire fields to typed app events.",
    details: [
      "The parser joins the prior remainder with each decoded text chunk.",
      "event names the type and data lines carry the payload.",
      "Cancellation belongs at the reader and adapter boundary; render buffering is a separate policy.",
    ],
    example: "event: token plus data: {\"delta\":\"hi\"} becomes a typed token event only after the frame's blank line.",
  },
  "Request and attempt identity": {
    subjectId: "llm-serving",
    module: "LLM Serving",
    lesson: "Reliability and Observability",
    definition: "A logical generation keeps one logical request ID while every retry receives a new attempt ID.",
    details: [
      "Events, logs, metrics, cancellation, and resources carry the active attempt ID.",
      "A delayed event from an older attempt must not change the current conversation.",
      "Separate IDs let operators trace one user request across several tries.",
    ],
    example: "Logical request r-201 can move from failed attempt r-201.1 to successful attempt r-201.2.",
  },
  "Safe retries and late-event guards": {
    subjectId: "llm-serving",
    module: "LLM Serving",
    lesson: "Reliability and Observability",
    definition: "Without a verified resume or deduplication protocol, automatically restarting a generation is safe only after a transient failure before visible output and while attempts remain.",
    details: [
      "Once tokens are visible, a from-scratch retry can duplicate or contradict them.",
      "Only active nonterminal requests accept events from the matching attempt.",
      "Queue, prefill, TTFT, decode, result, and resource release should be measured separately.",
    ],
    example: "A transient timeout with zero emitted tokens may retry; after three visible tokens, the app should not automatically restart from scratch.",
  },
  "Normalized conversation state": {
    subjectId: "chat-integration",
    module: "Chat Integration",
    lesson: "Conversation State",
    definition: "Normalized state stores message order as ids and keeps each message record once in a lookup table.",
    details: [
      "Rendering follows messageIds while messagesById owns the records.",
      "A stream delta targets a stable id instead of assuming the last array item is active.",
      "Reducer updates replace only the target record and leave earlier state untouched.",
    ],
    example: "Appending a delta to m-a1 creates a new m-a1 record without rewriting every other message.",
  },
  "Message, attempt, and request IDs": {
    subjectId: "chat-integration",
    module: "Chat Integration",
    lesson: "Conversation State",
    definition: "messageId names a UI record, attemptId names one model try, and requestId names one transport run.",
    details: [
      "The three identities have different lifetimes and should not be collapsed.",
      "Regeneration can create new attempt and request ids at the same conversation branch point.",
      "Controls such as canStop and canRegenerate should be derived from current records.",
    ],
    example: "One assistant message can stay in place while a regenerated attempt receives a fresh transport request.",
  },
  "Render buffering": {
    subjectId: "chat-integration",
    module: "Chat Integration",
    lesson: "Streaming React",
    definition: "A render buffer groups ordered token deltas into fewer React updates.",
    details: [
      "Transport parsing happens outside React and dispatches typed actions.",
      "An animation-frame flush joins exact text without adding separators or changing order.",
      "Buffering screen commits must not delay cancellation of the underlying generation.",
    ],
    example: "Deltas [“Hel”, “lo”, “ ”, “world”] can become one frame update: “Hello world”.",
  },
  "Scroll and live-region policy": {
    subjectId: "chat-integration",
    module: "Chat Integration",
    lesson: "Streaming React",
    definition: "Streaming UI should follow the reader only near the bottom and announce meaningful batches instead of every token.",
    details: [
      "If the reader scrolls up, auto-scroll should stop.",
      "A small distance threshold absorbs layout and font changes near the bottom.",
      "Live regions should receive grouped updates and one clear completion announcement.",
    ],
    example: "A reader 24 px from the bottom may follow new text, but an explicit scroll-up should override that.",
  },
  "Conversation branching": {
    subjectId: "chat-integration",
    module: "Chat Integration",
    lesson: "Actions and Context",
    definition: "Stop, retry, regenerate, and edit create explicit state transitions and branches instead of overwriting history.",
    details: [
      "Stop keeps partial assistant text and marks the attempt cancelled.",
      "Retry or regenerate starts a new assistant attempt from the same user message.",
      "Editing a user message creates a new branch and invalidates dependent descendants without deleting them.",
    ],
    example: "Two regenerations can share one parent user message while keeping separate attempt and request ids.",
  },
  "Context budgeting": {
    subjectId: "chat-integration",
    module: "Chat Integration",
    lesson: "Actions and Context",
    definition: "A context builder reserves required inputs, then adds complete history turns that fit a fixed token budget.",
    details: [
      "System instructions and the active user prompt are required.",
      "Choose complete user-assistant pairs newest first, then send selected pairs in chronological order.",
      "Report overflow if required inputs exceed budget, and never include half a turn.",
    ],
    example: "A 14-token budget may fit system + newest complete pair + active prompt while leaving an older pair out.",
  },
  "Saved-history validation": {
    subjectId: "chat-integration",
    module: "Chat Integration",
    lesson: "Product Quality",
    definition: "Conversation history loaded after refresh is untrusted input and must pass a strict versioned schema.",
    details: [
      "Accept exact safe fields, known roles and backends, and bounded content sizes.",
      "Restore only terminal messages such as complete, cancelled, or error—not an interrupted streaming state.",
      "Reject unexpected fields that could accidentally hold secrets.",
    ],
    example: "A final message may be restored, while the same record with an apiKey field must be rejected.",
  },
  "Generation lifecycle and recovery": {
    subjectId: "chat-integration",
    module: "Chat Integration",
    lesson: "Product Quality",
    definition: "One request lifecycle should drive visible status, controls, cleanup, and recovery behavior.",
    details: [
      "Queued, loading, prefill, and streaming are active phases; complete, cancelled, and error are terminal.",
      "Recovery rejects late events, releases resources, labels partial output, and returns focus predictably.",
      "Automated contracts cannot replace hands-on keyboard, screen-reader, touch, and mobile layout checks.",
    ],
    example: "After Stop, the app marks output stopped, releases the stream, and moves focus to a predictable control.",
  },
});

const coreSourceByLesson: Readonly<Record<string, string>> = {
  "linear-algebra:Arrays and Shapes": "NumPy Developers, NumPy absolute basics; Zhang et al., Dive into Deep Learning: Linear Algebra (2023).",
  "linear-algebra:Vector Operations": "Zhang et al., Dive into Deep Learning: Linear Algebra (2023); Deisenroth et al., Mathematics for Machine Learning (2020).",
  "linear-algebra:Dot Products": "Zhang et al., Dive into Deep Learning: Linear Algebra (2023); Deisenroth et al., Mathematics for Machine Learning (2020).",
  "linear-algebra:Matrix Multiplication": "NumPy Developers, numpy.matmul specification; Zhang et al., Dive into Deep Learning: Linear Algebra (2023).",
  "linear-algebra:Batches and Broadcasting": "NumPy Developers, NumPy broadcasting guide; NumPy Developers, numpy.matmul specification; Zhang et al., Dive into Deep Learning: Linear Algebra (2023).",
  "machine-learning-basics:Training and Validation Data": "Google Machine Learning Crash Course, Datasets, generalization, and overfitting; scikit-learn, Cross-validation.",
  "machine-learning-basics:Linear Regression": "Google Machine Learning Crash Course, Linear regression; Goodfellow, Bengio, and Courville, Deep Learning, Machine Learning Basics (2016).",
  "machine-learning-basics:Gradient Descent": "Google Machine Learning Crash Course, Gradient descent; Goodfellow, Bengio, and Courville, Deep Learning, Numerical Computation (2016).",
  "machine-learning-basics:Binary Classification": "Google Machine Learning Crash Course, Sigmoid and classification; Goodfellow, Bengio, and Courville, Deep Feedforward Networks (2016).",
  "machine-learning-basics:Neural Networks": "Google Machine Learning Crash Course, Neural networks; Goodfellow, Bengio, and Courville, Deep Feedforward Networks (2016).",
  "model-foundations:Character RNNs": "Karpathy, The Unreasonable Effectiveness of Recurrent Neural Networks (2015); Hochreiter and Schmidhuber, Long Short-Term Memory (1997); Gers, Schmidhuber, and Cummins, Learning to Forget (2000).",
  "model-foundations:Neural Language Models": "Bengio et al., A Neural Probabilistic Language Model (2003); Mikolov et al., Efficient Estimation of Word Representations in Vector Space (2013); Mikolov et al., Distributed Representations of Words and Phrases and their Compositionality (2013).",
  "model-foundations:Subword Tokenization": "Sennrich, Haddow, and Birch, Neural Machine Translation of Rare Words with Subword Units (2016); Kudo and Richardson, SentencePiece (2018).",
  "model-foundations:Additive Attention": "Bahdanau, Cho, and Bengio, Neural Machine Translation by Jointly Learning to Align and Translate (2014); Luong, Pham, and Manning, Effective Approaches to Attention-based Neural Machine Translation (2015); Xu et al., Show, Attend and Tell (2015).",
  "model-foundations:Transformers": "Vaswani et al., Attention Is All You Need (2017); Radford et al., Improving Language Understanding by Generative Pre-Training (2018).",
  "model-foundations:In-Context Learning": "Brown et al., Language Models are Few-Shot Learners (2020); Min et al., Rethinking the Role of Demonstrations (2022); Garg et al., What Can Transformers Learn In-Context? (2022).",
  "inference-runtime:Inference Runtime": "PagedAttention (Kwon et al., 2023); FlashAttention (Dao et al., 2022); Ainslie et al., GQA: Training Generalized Multi-Query Transformer Models from Multi-Head Checkpoints (2023); Hugging Face Cache strategies guide; MDN Web Workers API.",
  "inference-runtime:Scheduling and Memory": "Orca (Yu et al., 2022); PagedAttention/vLLM (Kwon et al., 2023); Sarathi-Serve (Agrawal et al., 2024).",
  "llm-serving:Streaming Transport": "WHATWG HTML Server-sent events; WHATWG Streams Standard; MDN Using server-sent events.",
  "llm-serving:Reliability and Observability": "Google SRE Monitoring Distributed Systems and Alerting on SLOs; OpenTelemetry Traces concepts, Trace specification, and Sampling guide.",
  "chat-integration:Conversation State": "React official guides: Extracting State Logic into a Reducer, Choosing the State Structure, and Preserving and Resetting State.",
  "chat-integration:Streaming React": "MDN Using readable streams; WHATWG Streams Standard; React official useTransition and state queueing guides.",
  "chat-integration:Actions and Context": "OpenAI Conversation state guide; MDN AbortController; React Queueing a Series of State Updates.",
  "chat-integration:Product Quality": "W3C WCAG 2.2 ARIA23 and Status Messages guidance; web.dev Interaction to Next Paint; course-authored Product Quality storage-validation contract.",
};

const sourcedCoreFlashcardLibrary = defineFlashcardLibrary(Object.fromEntries(
  Object.entries(coreFlashcardLibrary).map(([concept, value]) => {
    const source = coreSourceByLesson[`${value.subjectId}:${value.lesson}`];
    if (!source) throw new Error(`Missing core flash-card source trail: ${concept}`);
    return [concept, { ...value, source }];
  }),
));

export const flashcardLibrary = combineFlashcardLibraries(
  sourcedCoreFlashcardLibrary,
  foundationExpansionLibrary,
  modelFoundationsExpansionLibrary,
  systemsAndProductExpansionLibrary,
);
export type FlashcardConcept = keyof typeof flashcardLibrary;
export const flashcards = buildFlashcards(flashcardLibrary);
