import type { ExerciseContract } from "@/examples/learning-platform/llm-learning/lessons/exercise-contracts";

function contract(
  signature: string,
  inputs: string,
  output: string,
  rule: string,
  example: string,
): ExerciseContract {
  return { signature, inputs, output, rule, example };
}

export const foundationExerciseContractCopy: Record<string, ExerciseContract> = {
  "arrays-and-shapes/describe-array": contract(
    "def describe_array(values):",
    "values: one scalar or a rectangular nested numerical array",
    "dict with rank, shape, and size",
    "Read ndim, shape, and size without changing the values.",
    "[[1,2,3],[4,5,6]] → {rank: 2, shape: [2,3], size: 6}",
  ),
  "arrays-and-shapes/reshape-array": contract(
    "def reshape_array(values, shape):",
    "values: flat numerical vector; shape: [positive rows, positive columns]",
    "matrix with the requested rows and columns",
    "rows × columns must equal the original number of values.",
    "[1,2,3,4,5,6], [2,3] → [[1,2,3],[4,5,6]]",
  ),
  "vector-operations/add-vectors": contract(
    "def add_vectors(left, right):",
    "left and right: equal-length numerical vectors",
    "list with one sum per coordinate",
    "Add values at matching positions.",
    "[1,2,3] + [4,-2,0] → [5,0,3]",
  ),
  "vector-operations/l2-norm": contract(
    "def l2_norm(vector):",
    "vector: one-dimensional numerical array",
    "non-negative float",
    "Return sqrt(sum(value²)).",
    "[3,4] → 5",
  ),
  "dot-products/dot-product": contract(
    "def dot_product(left, right):",
    "left and right: equal-length numerical vectors",
    "one finite float",
    "Multiply matching coordinates, then add every product.",
    "[1,2,3] · [4,-1,2] → 8",
  ),
  "dot-products/cosine-similarity": contract(
    "def cosine_similarity(left, right):",
    "two equal-length, nonzero numerical vectors",
    "float between -1 and 1",
    "Divide the dot product by the product of both L2 norms.",
    "[1,2], [2,4] → 1",
  ),
  "matrix-multiplication/matrix-vector-product": contract(
    "def matrix_vector_product(matrix, vector):",
    "matrix [rows × columns], vector [columns]",
    "list[float] with one value per matrix row",
    "Compute one dot product between each row and the vector.",
    "[[1,2],[3,4]] @ [2,-1] → [0,2]",
  ),
  "matrix-multiplication/linear-layer": contract(
    "def linear_layer(vector, weights, bias):",
    "vector [inputs], weights [outputs × inputs], bias [outputs]",
    "list[float] with shape [outputs]",
    "Return weights @ vector + bias.",
    "zero vector with bias [5,-2] → [5,-2]",
  ),
  "batches-and-broadcasting/add-row-bias": contract(
    "def add_row_bias(rows, bias):",
    "rows [batch × width], bias [width]",
    "nested list with the same shape as rows",
    "Add one output-baseline vector to every row; do not create a different bias per row.",
    "[[0,0],[3,4]] + [10,-1] → [[10,-1],[13,3]]",
  ),
  "batches-and-broadcasting/batch-linear": contract(
    "def batch_linear(inputs, weights, bias):",
    "inputs [batch × in], weights [out × in], bias [out]",
    "nested list with shape [batch × out]",
    "Return inputs @ weights.T + bias for the full batch.",
    "two input rows and two output weights → two output rows",
  ),
  "ml-training-data/features-targets": contract(
    "def features_and_targets(rows):",
    "rectangular rows with at least one feature and one final target column",
    "dict containing feature rows and target values",
    "Use every column except the last as features and the last column as target.",
    "[[1,2,0],[3,4,1]] → features [[1,2],[3,4]], targets [0,1]",
  ),
  "ml-training-data/holdout-split": contract(
    "def holdout_split(features, targets, validation_indices):",
    "matching feature/target rows and unique in-range validation indices",
    "ordered training and validation feature/target arrays",
    "Put selected indices in validation and every other row in training, with no duplicates.",
    "indices [1,3] from four rows → training 0,2 and validation 1,3",
  ),
  "ml-linear-regression/linear-prediction": contract(
    "def linear_prediction(features, weights, bias):",
    "equal-length feature and weight vectors plus one bias",
    "one finite float prediction",
    "Return dot(features, weights) + bias.",
    "[2,-1], [3,4], 0.5 → 2.5",
  ),
  "ml-linear-regression/mean-squared-error": contract(
    "def mean_squared_error(predictions, targets):",
    "non-empty, equal-length prediction and target vectors",
    "non-negative float",
    "Average (prediction - target)² over the batch.",
    "[2,4], [1,6] → 2.5",
  ),
  "ml-gradient-descent/mse-gradients": contract(
    "def mse_gradients(xs, targets, weight, bias):",
    "matching non-empty x and target vectors plus scalar weight and bias",
    "dict with scalar weight and bias gradients",
    "Average 2·error·x for weight and 2·error for bias.",
    "x [1,2], y [2,4], w 0, b 0 → {weight: -10, bias: -6}",
  ),
  "ml-gradient-descent/gradient-step": contract(
    "def gradient_step(weight, bias, gradients, learning_rate):",
    "scalar parameters, both gradients, and a non-negative learning rate",
    "dict containing the updated weight and bias",
    "Subtract learning_rate × gradient from each parameter.",
    "w 1, b 0, gradients {-2,1}, rate .1 → {1.2,-.1}",
  ),
  "ml-binary-classification/sigmoid": contract(
    "def sigmoid(logit):",
    "one finite real-valued logit",
    "finite probability from 0 through 1",
    "Use a numerically stable sigmoid branch for positive and negative logits.",
    "0 → 0.5; 2 → about 0.881",
  ),
  "ml-binary-classification/binary-cross-entropy": contract(
    "def binary_cross_entropy(probabilities, targets):",
    "equal non-empty vectors of probabilities and binary targets",
    "mean non-negative float loss",
    "Average -[y log p + (1-y) log(1-p)] with a small log-safety clamp.",
    "[.9,.2], [1,0] → about .164",
  ),
  "ml-neural-networks/relu": contract(
    "def relu(values):",
    "one-dimensional numerical vector",
    "list with the same length",
    "Replace each negative coordinate with zero and keep the others.",
    "[-2,0,3] → [0,0,3]",
  ),
  "ml-neural-networks/two-layer-network": contract(
    "def two_layer_network(features, parameters):",
    "feature vector and W1, b1, W2, b2 with matching dimensions",
    "one finite output logit",
    "Compute hidden = ReLU(W1 @ x + b1), then W2 @ hidden + b2.",
    "identity hidden layer with x [2,-1] → ReLU keeps [2,0]",
  ),
};
