import {
  combineFlashcardLibraries,
  defineFlashcardGroup,
} from "../flashcard-schema";

function card(
  definition: string,
  detailOne: string,
  detailTwo: string,
  detailThree: string,
  example: string,
) {
  return {
    definition,
    details: [detailOne, detailTwo, detailThree] as const,
    example,
  };
}

const inferenceMechanics = defineFlashcardGroup(
  {
    subjectId: "inference-runtime",
    module: "Inference Runtime",
    lesson: "Inference Runtime",
    source: "PagedAttention (Kwon et al., 2023); FlashAttention (Dao et al., 2022); Ainslie et al., GQA: Training Generalized Multi-Query Transformer Models from Multi-Head Checkpoints (2023); Hugging Face Cache strategies guide; MDN Web Workers API.",
  },
  {
    "Autoregressive inference": card(
      "Autoregressive inference generates one new token from the prompt and all tokens that came before it.",
      "Each sampled token becomes part of the input prefix for the next step.",
      "Later output positions depend on earlier samples, so they cannot all be generated independently.",
      "The model weights stay fixed while activations and cached attention state grow.",
      "After sampling “blue,” the next forward pass conditions on the prompt plus the new word “blue.”",
    ),
    "Prefill phase": card(
      "The prefill phase processes every prompt position together and builds the initial attention cache.",
      "Parallel prompt processing makes prefill different from one-token-at-a-time decoding.",
      "The final prompt position produces the scores used for the first output token.",
      "Long prompts can make prefill the largest part of the first-token wait.",
      "A 96-token prompt enters one prefill pass before any generated token appears on screen.",
    ),
    "Decode phase": card(
      "The decode phase repeatedly advances generation by one position after the first token has been sampled.",
      "Each decode forward reads the existing cache and adds state for one more processed position.",
      "Generating N output tokens needs at most N minus one later decode forwards.",
      "Decode is sequential across positions even when many requests share one batch.",
      "A 32-token answer uses 31 decode forwards because token one comes from the prefill scores.",
    ),
    "Prefill logits": card(
      "Prefill logits are the raw vocabulary scores at the final prompt position before sampling the first output token.",
      "A logit is not a probability until a normalization or sampling rule is applied.",
      "Temperature and token filters can change how the same logits are sampled.",
      "The selected first token does not require an extra decode forward of its own.",
      "If “yes” has the highest final-position score, sampling may choose it directly from the prefill output.",
    ),
    "KV cache": card(
      "A KV cache stores attention key and value vectors for earlier positions so generation can reuse them.",
      "Each cached-attention layer keeps its own cached keys and values.",
      "The cache grows as more prompt and generated positions are processed.",
      "Reusing cached state avoids recomputing attention representations for the full prefix each step.",
      "At token 40, the model reads cached state for the preceding positions instead of rebuilding all 39 of them.",
    ),
    "Cached sequence position": card(
      "A cached sequence position is one prompt or generated position whose key and value vectors have been stored.",
      "Prompt positions enter the cache together during prefill.",
      "Later generated positions normally enter the cache one decode step at a time.",
      "The last sampled token may be in the final text before it has ever been processed into the cache.",
      "A prompt of 96 plus 31 later forwards can yield 127 cached positions but a 128-token final sequence.",
    ),
    "KV-cache geometry": card(
      "KV-cache geometry is the model and sequence shape that determines how many cached numeric values are stored.",
      "Layer count multiplies memory because every layer owns separate cached state.",
      "KV-head count and head dimension determine the vector width stored at each position.",
      "Token count and bytes per numeric value scale the final storage requirement directly.",
      "Four layers, eight KV heads, dimension 16, and 100 positions stored as 16-bit (2-byte) values require 204,800 bytes.",
    ),
    "Grouped-query attention (GQA)": card(
      "Grouped-query attention lets several query heads share a smaller set of key-value heads.",
      "Query-head count can therefore be larger than the KV-head count.",
      "Cache sizing must use KV heads because only key and value vectors are retained.",
      "Sharing reduces cache memory while preserving multiple learned query projections.",
      "A model with 32 query heads and 8 KV heads stores eight key vectors and eight value vectors per position.",
    ),
    "Time to first token (TTFT)": card(
      "Time to first token measures the delay from a stated request boundary until the first generated token crosses a stated output boundary.",
      "A report must say whether it ends at server emission, client receipt, or visual rendering because those boundaries produce different values.",
      "Model loading and prompt prefill may also contribute to this measurement.",
      "TTFT says nothing about how quickly later tokens continue to arrive.",
      "An 18 ms server queue plus a 74 ms prefill produces a 92 ms server-emitted TTFT, before network and rendering delay.",
    ),
    "Inter-token latency (ITL)": card(
      "Inter-token latency measures the time gaps between consecutive generated tokens at a stated observation boundary after the first token.",
      "ITL describes the ongoing rhythm of a streamed answer rather than its initial wait.",
      "Server-emitted, client-received, and visually rendered gaps should not be compared without naming their different measurement boundaries.",
      "Scheduling pauses or memory pressure can create occasional slow gaps even when average speed looks good.",
      "Tokens received by a client at 100, 145, and 190 ms have two client-received inter-token gaps of 45 ms.",
    ),
    "Decode throughput": card(
      "Decode throughput is the steady rate at which a runtime produces output tokens, commonly shown as tokens per second.",
      "It should be measured over the decode interval rather than including prompt queue time.",
      "Higher throughput does not guarantee a low first-token delay for one request.",
      "Batch-wide throughput and per-request token rate answer different performance questions.",
      "Producing 42 later tokens in two seconds gives a decode rate of 21 tokens per second.",
    ),
    "Memory-bandwidth-bound decode": card(
      "Memory-bandwidth-bound decode spends more time moving model and cache data than performing arithmetic.",
      "One-token decode offers less parallel work than processing a full prompt.",
      "Reading large weights and growing KV state can dominate each short computation step.",
      "Adding arithmetic units alone will not fix a bottleneck caused by data movement.",
      "A GPU may show low compute use while each decode step waits for weights to arrive from device memory.",
    ),
    PagedAttention: card(
      "PagedAttention stores a request’s logical KV blocks in reusable physical blocks that need not be contiguous.",
      "The design borrows page mapping ideas from operating-system virtual memory.",
      "A block table translates each request’s logical order into physical cache locations.",
      "Flexible mapping reduces reserved empty space when request lengths vary.",
      "Logical blocks 0, 1, and 2 can map to physical blocks 7, 19, and 4 while preserving sequence order.",
    ),
    "Copy-on-write KV blocks": card(
      "Copy-on-write KV blocks let several sequences share physical attention-cache blocks until one sequence needs to change a shared block.",
      "Each sequence’s block table can point to the same reference-counted physical blocks for an identical prefix.",
      "Reading a shared prefix does not copy its key and value vectors or give either sequence permission to alter them.",
      "Before a write to a multiply owned block, the allocator copies that block and redirects only the writing sequence.",
      "Two sampled answers share four prompt blocks; when one extends their partly filled last block, it receives a private copy while the first three stay shared.",
    ),
    "KV-cache fragmentation": card(
      "KV-cache fragmentation is memory that exists but cannot be used efficiently because allocation leaves gaps or oversized reservations.",
      "Internal fragmentation is unused capacity inside an allocated block.",
      "External fragmentation is free capacity split into pieces that cannot satisfy a contiguous request.",
      "Paged allocation reduces large contiguous reservations but does not make all waste impossible.",
      "Reserving 2,048 positions for a 300-token request strands 1,748 positions even though the memory is marked occupied.",
    ),
    "IO-aware attention": card(
      "IO-aware attention designs the algorithm around reads and writes between levels of accelerator memory.",
      "I/O means data movement; FlashAttention tiles work so intermediate values stay in small, fast on-chip static RAM (SRAM).",
      "Reducing transfers to larger device high-bandwidth memory, or HBM, can improve wall-clock speed without approximating attention.",
      "Arithmetic complexity alone does not predict speed when memory movement dominates.",
      "A tiled kernel reuses a loaded key block in SRAM instead of repeatedly fetching it from HBM.",
    ),
    "Web Worker isolation": card(
      "Web Worker isolation runs browser inference on a background thread instead of React’s main UI thread.",
      "Worker messages form an explicit boundary between model state and product state.",
      "Heavy model computation cannot directly block input handlers, layout, or painting.",
      "Cancellation and errors still need structured messages back to the main thread.",
      "The composer remains responsive while a worker processes a long prompt and posts token events back to React.",
    ),
    "KV-cache strategy": card(
      "A KV-cache strategy chooses how cached state grows, where it lives, and how precisely its numbers are stored.",
      "Dynamic caches grow with the sequence, while static caches reserve a fixed maximum shape.",
      "Offloading trades device memory for CPU-transfer cost and may reduce generation speed.",
      "Quantized caches use fewer bits per value but add conversion work and possible quality risk.",
      "A small GPU can retry with an offloaded cache after an out-of-memory error instead of dropping the request.",
    ),
  },
);

const schedulingAndMemory = defineFlashcardGroup(
  {
    subjectId: "inference-runtime",
    module: "Inference Runtime",
    lesson: "Scheduling and Memory",
    source: "Orca (Yu et al., 2022); PagedAttention/vLLM (Kwon et al., 2023); Sarathi-Serve (Agrawal et al., 2024).",
  },
  {
    "Static batching": card(
      "Static batching keeps the same requests together until the longest member of that batch has finished.",
      "A short request can stop producing useful tokens while its slot remains reserved.",
      "New arrivals wait even when some batch members have already completed.",
      "The policy is simple but wastes capacity when output lengths differ greatly.",
      "If A finishes at step 4 and B at step 20, A’s slot can sit idle for the remaining 16 steps.",
    ),
    "Iteration-level scheduling": card(
      "Iteration-level scheduling reconsiders which requests run after each model iteration rather than after a whole batch.",
      "Autoregressive generation naturally exposes a decision point after each token step.",
      "Completed work can leave before the longest request is done.",
      "Waiting requests may enter at the next safe iteration boundary.",
      "After request A finishes token 12, the scheduler can admit D before B and C finish their longer outputs.",
    ),
    "Selective batching": card(
      "Selective batching is Orca’s policy of batching only operations whose shapes are compatible, rather than forcing every operation in an iteration through one batch.",
      "Orca divides a model iteration into individual operations instead of treating the entire model as one indivisible batch.",
      "Attention runs per request because requests can have different cache lengths.",
      "Compatible non-attention operations batch across requests while each request’s operation order stays intact.",
      "Three requests run attention separately, then execute their same-shaped feed-forward operation together.",
    ),
    "Admission control": card(
      "Admission control decides whether a queued request may enter active inference under current resource limits.",
      "The decision considers free batch slots and available KV-cache pages.",
      "A token or memory budget can reject work that would overcommit the runtime.",
      "Priority and fairness rules may affect which eligible request enters first.",
      "A request needing six pages stays queued when only four are free, even though a decode slot is open.",
    ),
    "Scheduler fairness": card(
      "Scheduler fairness prevents one class of requests from waiting indefinitely while other work repeatedly passes it.",
      "Always favoring short prompts can starve a long document request.",
      "Always favoring old work can make interactive chat feel unresponsive.",
      "Fair policies balance age, size, priority, and resource cost explicitly.",
      "A waiting request gains priority each round until it is admitted despite newer short chats arriving.",
    ),
    "Physical KV page": card(
      "A physical KV page is a fixed-capacity block of actual cache memory assigned through a request’s page mapping.",
      "One page holds a fixed number of token positions for a model’s cached vectors.",
      "Pages for one request do not need adjacent physical addresses.",
      "The allocator can reuse a released page for an unrelated later request.",
      "Request A’s third logical page can occupy physical page 41 and later be reassigned to request D.",
    ),
    "Ceiling division": card(
      "Ceiling division rounds a partial allocation unit upward so every required token position has capacity.",
      "The integer formula is (tokens + page size - 1) divided with floor division.",
      "Using ordinary floor division underallocates whenever a remainder exists.",
      "Adding one unconditionally overallocates zero and exact page multiples.",
      "With 33 tokens and page size 16, ceiling division allocates three pages rather than two or four.",
    ),
    "Internal page waste": card(
      "Internal page waste is the unused capacity inside the final allocated page for a request.",
      "Waste equals allocated page capacity minus the request’s cached token count.",
      "Correct ceiling allocation keeps the waste below one full page.",
      "An exact multiple of page size has zero internal page waste.",
      "Thirty-three tokens in three 16-slot pages leave 15 unused positions in the last page.",
    ),
    "Page reclamation": card(
      "Page reclamation returns cache pages from finished or cancelled requests to the free pool.",
      "A completion record must retain identity long enough to release the right resources.",
      "Reclamation should happen before the next admission decision when possible.",
      "Leaked pages gradually reduce capacity even when no requests remain active.",
      "When request B completes, its five pages are freed and request E can enter the next iteration.",
    ),
    "Capacity utilization": card(
      "Capacity utilization measures how much available serving capacity performs useful request work.",
      "Idle slots from completed static-batch members reduce utilization.",
      "Allocated but unused page positions also consume capacity without useful tokens.",
      "A higher percentage is meaningful only under the same workload and resource limits.",
      "Using 86 of 100 available slot-iterations gives 86 percent capacity utilization.",
    ),
    "Throughput-latency tradeoff": card(
      "The throughput-latency tradeoff describes how maximizing total work can increase the wait experienced by one request.",
      "Larger batches often improve accelerator utilization and aggregate token output.",
      "Waiting to form or preserve a large batch can raise queue and inter-token latency.",
      "The best policy depends on workload shape and the product’s latency objective.",
      "Holding a chat request 40 ms to join a fuller batch may raise total tokens per second but worsen its TTFT.",
    ),
    "Chunked prefill": card(
      "Chunked prefill divides a long prompt’s compute into smaller pieces that can be scheduled between decode work.",
      "A chunk processes only part of the prompt while preserving the final prefill result.",
      "Smaller chunks reduce the length of any single compute-heavy interruption.",
      "Very small chunks can add scheduling overhead and reduce prompt-processing efficiency.",
      "A 4,096-token prompt can run as eight 512-token chunks while active chats continue decoding.",
    ),
    "Prefill interference": card(
      "Prefill interference is the delay imposed on active decoding when compute-heavy prompt work shares its resources.",
      "Prefill typically uses more parallel compute than a one-token decode step.",
      "An unchunked long prompt can create a visible pause in existing streams.",
      "Measuring only average throughput can hide these per-token stalls.",
      "An active chat’s next token waits 180 ms because a large document prefill monopolizes the intervening iteration.",
    ),
    "Stall-free scheduling": card(
      "Stall-free scheduling admits prompt work in a way that limits pauses in ongoing decode streams.",
      "Chunk size can be chosen to fit beside a target amount of decode work.",
      "The policy seeks high throughput without large inter-token latency spikes.",
      "It reduces interference but cannot eliminate every resource or queue tradeoff.",
      "The scheduler pairs one 256-token prefill chunk with each decode round instead of running the full prompt at once.",
    ),
  },
);

const streamingTransport = defineFlashcardGroup(
  {
    subjectId: "llm-serving",
    module: "LLM Serving",
    lesson: "Streaming Transport",
    source: "WHATWG HTML Server-sent events; WHATWG Streams Standard; MDN Using server-sent events.",
  },
  {
    "Server-Sent Events (SSE)": card(
      "Server-Sent Events is a one-way text protocol for sending a continuing sequence of optionally named events to a client.",
      "The server keeps one HTTP response open and writes events over time.",
      "The format is UTF-8 text with fields separated into blank-line-terminated blocks.",
      "SSE includes event identity and reconnection rules beyond simple newline-delimited JSON.",
      "A generation server can send token events followed by metrics and one final done event on the same response.",
    ),
    "text/event-stream MIME type": card(
      "The text/event-stream media type, also called a MIME type, tells a client that an HTTP response follows the Server-Sent Events format.",
      "A conforming EventSource connection expects this response content type.",
      "The stream is decoded as UTF-8 rather than using a caller-selected character set.",
      "A normal JSON content type does not activate the same event-stream interpretation rules.",
      "A server returns Content-Type: text/event-stream before writing event and data fields incrementally.",
    ),
    EventSource: card(
      "EventSource is the browser interface for opening an SSE connection and receiving dispatched message events.",
      "Its readyState reports connecting, open, or closed connection state.",
      "It automatically attempts reconnection after many network closures.",
      "Calling close stops the fetch work and moves the interface to the closed state.",
      "A page creates new EventSource('/events') and listens for token messages until the server finishes.",
    ),
    "UTF-8 byte boundary": card(
      "A UTF-8 byte boundary marks the start or end of an encoded character and may not align with a network chunk.",
      "Characters outside basic ASCII commonly occupy two, three, or four bytes.",
      "Decoding each byte chunk independently can replace a split character with an error marker.",
      "Byte boundaries are also unrelated to JSON, token, or SSE-frame boundaries.",
      "The euro sign bytes e2 82 ac may arrive as e2 82 and ac but must still produce one “€” character.",
    ),
    "Streaming TextDecoder": card(
      "A streaming TextDecoder converts incoming bytes to text while retaining any incomplete character for the next chunk.",
      "Passing stream: true tells the decoder that more bytes may still arrive.",
      "A final flush handles any bytes remaining when the response ends.",
      "The frame parser should receive decoded strings rather than raw Uint8Array values.",
      "The first chunk ends halfway through “€” and returns prior text; the next chunk completes and emits the character.",
    ),
    "Incremental frame parser": card(
      "An incremental frame parser emits complete protocol frames while saving unfinished decoded text for later input.",
      "It prepends the prior remainder before searching the new combined text.",
      "One chunk may contain zero, one, or many complete frames.",
      "Supporting carriage return (CR), line feed (LF), and carriage-return-plus-line-feed (CRLF) endings prevents line-ending assumptions from corrupting valid input.",
      "Chunk one can end with `data: {\"delta\":\"h`; chunk two supplies `i\"}\\n\\n`, completing one token event.",
    ),
    "Blank-line frame terminator": card(
      "A blank line terminates an SSE event block and tells the parser that its accumulated fields may be dispatched.",
      "The separator can use carriage return (CR), line feed (LF), or carriage-return-plus-line-feed (CRLF) endings.",
      "A single newline ends a field line but does not finish the event.",
      "End-of-stream alone does not dispatch a final block missing its blank line.",
      "The text data: ready followed by two newline characters dispatches one default message event.",
    ),
    "Parser remainder": card(
      "A parser remainder is the incomplete decoded suffix carried from one stream chunk into the next call.",
      "Only text after the last complete frame separator belongs in the remainder.",
      "Discarding it loses events that span arbitrary chunk boundaries.",
      "Emitting it early exposes partial JSON or protocol fields to application code.",
      "After parsing one full frame plus event: token, the unfinished event line becomes the next call’s remainder.",
    ),
    "SSE data field": card(
      "An SSE data field contributes text to the message payload that will be delivered when the event is dispatched.",
      "Each data line appends its value and one line-feed character to the data buffer.",
      "One optional space immediately after the colon is removed from the field value.",
      "Multiple data lines become one payload containing embedded newline characters.",
      "Two lines, data: first and data: second, dispatch the single payload “first\nsecond”.",
    ),
    "SSE event field": card(
      "An SSE event field sets the type of the browser event that will be dispatched for the current block.",
      "A nonempty event value replaces the default message type.",
      "Field names are compared literally rather than case-insensitively.",
      "Application adapters should allow only expected event names at their typed boundary.",
      "The line event: metrics makes the completed block dispatch as a metrics event instead of message.",
    ),
    "Last-Event-ID": card(
      "Last-Event-ID carries the most recently observed SSE event identifier when a client reconnects.",
      "An id field updates the connection’s stored last-event identifier.",
      "An empty id value resets the stored identifier and suppresses the reconnect header.",
      "The mechanism helps a server resume after a known event without blindly replaying everything.",
      "After receiving id: 418, a reconnect can send Last-Event-ID: 418 and resume with event 419.",
    ),
    "SSE retry field": card(
      "An SSE retry field asks the client to use a new reconnection delay measured in milliseconds.",
      "Only a field value made entirely of ASCII digits is accepted.",
      "The value changes reconnect timing rather than scheduling an application-level request retry.",
      "A malformed or negative-looking value is ignored by the event-stream parser.",
      "The line retry: 3000 tells EventSource to wait about three seconds before reconnecting.",
    ),
    "Typed transport adapter": card(
      "A typed transport adapter converts protocol-specific frames into a small set of application event shapes.",
      "React receives token, metrics, done, or error records instead of wire-format field strings.",
      "Payload validation belongs at this boundary before state is updated.",
      "Changing the backend protocol then requires changing the adapter rather than every UI component.",
      "A token frame with delta “hi” becomes {type: 'token', delta: 'hi'} before reducer dispatch.",
    ),
    "ReadableStream reader lock": card(
      "A ReadableStream reader lock gives one active reader exclusive access to consume a stream.",
      "Calling getReader locks the stream until that reader releases its lock.",
      "A second reader cannot be acquired while the first remains active.",
      "Cancellation and normal completion should release reader-owned resources predictably.",
      "The transport loop gets one reader, consumes chunks, then releases the lock in its cleanup block.",
    ),
    "Stream backpressure": card(
      "Stream backpressure is feedback that tells a producer when queued data is accumulating faster than consumption.",
      "A high-water mark defines the queue level where pressure should be applied.",
      "Desired size reports how much more data the queue can accept under its strategy.",
      "UI render buffering does not automatically stop network parsing or create protocol backpressure.",
      "When desiredSize reaches zero, a pull-based source waits instead of enqueueing another large byte chunk.",
    ),
    "AbortSignal propagation": card(
      "AbortSignal propagation carries one cancellation decision through every layer that owns ongoing asynchronous work.",
      "The fetch or local generator should observe the same signal as the stream reader.",
      "The parser must discard its unfinished remainder after cancellation.",
      "Stopping React updates alone is insufficient because hidden generation would keep consuming resources.",
      "Pressing Stop aborts the response reader, halts the worker generator, clears pending text, and releases cache pages.",
    ),
  },
);

const reliabilityAndObservability = defineFlashcardGroup(
  {
    subjectId: "llm-serving",
    module: "LLM Serving",
    lesson: "Reliability and Observability",
    source: "Google SRE Monitoring Distributed Systems and Alerting on SLOs; OpenTelemetry Traces concepts, Trace specification, and Sampling guide.",
  },
  {
    "Logical request ID": card(
      "A logical request ID identifies one user-visible generation from start to finish, even if that work is retried.",
      "The identifier remains stable across all attempts for the same requested answer.",
      "Logs and metrics can group several failures and retries under one user action.",
      "It should not be reused for a later independent prompt from the same conversation.",
      "The request r-201 keeps that ID when its first attempt times out and its second attempt succeeds.",
    ),
    "Attempt ID": card(
      "An attempt ID identifies one specific try to execute a logical generation request.",
      "Every retry receives a fresh attempt identifier.",
      "Stream events and owned resources carry the active attempt ID.",
      "Comparing it prevents a retired worker from updating the current conversation.",
      "Attempt a-17.1 fails before output, while a-17.2 becomes the only attempt allowed to emit tokens.",
    ),
    "Transient failure": card(
      "A transient failure is a temporary condition that may succeed when the same safe operation is tried again.",
      "Queue timeout, brief overload, or a retired worker can be transient categories.",
      "A permanent validation or authentication error should not use the same retry rule.",
      "Classification must reflect the actual error rather than assuming every failure is temporary.",
      "A worker startup timeout retries once, while malformed request data immediately returns an error.",
    ),
    "Retry budget": card(
      "A retry budget is the fixed maximum number of attempts allowed for one logical request.",
      "The budget prevents infinite retry loops during a persistent outage.",
      "An attempt index and a total attempt count must use one documented convention.",
      "Resource and latency costs increase each time another attempt is consumed.",
      "With maxAttempts equal to two, failed zero-based attempt 0 may retry but attempt 1 may not.",
    ),
    "Transparent retry boundary": card(
      "The transparent retry boundary is the last point where an automatic retry cannot duplicate user-visible output.",
      "A retry before any token is shown can replace a failed invisible attempt.",
      "Once text is visible, restarting may repeat or contradict that partial answer.",
      "The decision also requires a transient error and unused retry budget.",
      "A timeout at zero tokens retries automatically, while the same timeout after “The answer” remains an error with partial text.",
    ),
    "Terminal-state guard": card(
      "A terminal-state guard rejects new events after a request reaches complete, cancelled, or error state.",
      "Only explicitly active phases such as queued, loading, prefill, and streaming accept events.",
      "Unknown future states should fail closed rather than accept updates accidentally.",
      "Matching IDs do not make an event valid after the lifecycle has ended.",
      "A token carrying the correct attempt ID is still ignored when its message already says complete.",
    ),
    "Stale-event rejection": card(
      "Stale-event rejection ignores delayed work that belongs to a retired attempt or transport request.",
      "Event identity is checked before content or metrics touch application state.",
      "A retry changes attempt identity even though the logical request stays the same.",
      "Rejection should be observable so recurring races can be diagnosed.",
      "A token from a-1 arriving after a-2 starts is counted as stale and never appended to the answer.",
    ),
    "Failure injection": card(
      "Failure injection deliberately triggers known error paths so retry, cleanup, and user messaging can be verified.",
      "Fixed scenarios make timeouts, malformed frames, crashes, and aborts repeatable.",
      "Each scenario should assert final state and resource release, not only the visible error.",
      "Synthetic tests complement rather than reproduce real provider or regional outages.",
      "A seeded trace crashes the worker after prefill and verifies one bounded retry with fresh identity.",
    ),
    "Four golden signals": card(
      "The four golden signals are latency, traffic, errors, and saturation for a user-facing service.",
      "Latency should distinguish successful and failed work when their behavior differs.",
      "Traffic measures demand, such as requests or generated tokens over time.",
      "Saturation shows how close a constrained resource is to its practical limit.",
      "A serving dashboard charts request rate, p95 TTFT, error ratio, and used KV pages together.",
    ),
    "Tail latency": card(
      "Tail latency describes the slow end of a timing distribution rather than its average request.",
      "Percentiles such as p95 or p99 make unusually slow experiences visible.",
      "A small group of severe stalls can matter even when the mean remains acceptable.",
      "Queue, prefill, and inter-token tails should be inspected separately.",
      "Nine requests finish near 100 ms and one at 1,200 ms, producing a harmless-looking 210 ms average but a painful tail.",
    ),
    "Latency histogram": card(
      "A latency histogram counts timing observations in ranges so operators can study the full distribution.",
      "Buckets retain more shape information than one running average.",
      "Histogram data can estimate percentiles across many requests.",
      "Bucket boundaries should reflect the latency ranges users and objectives care about.",
      "TTFT observations are counted in 50, 100, 250, 500, and 1,000 ms buckets to reveal a slow cluster.",
    ),
    "Service-level indicator (SLI)": card(
      "A service-level indicator is a measured quantity that represents one aspect of user-visible service behavior.",
      "Examples include successful request ratio and the fraction of TTFT values below a threshold.",
      "The indicator needs a precise numerator, denominator, and measurement window.",
      "Internal health metrics are not automatically good SLIs unless they track user experience.",
      "One SLI is 9,970 successful terminal generations divided by 10,000 valid requests this week.",
    ),
    "Service-level objective (SLO)": card(
      "A service-level objective sets a target value for a service-level indicator over a stated time window.",
      "The objective turns vague reliability goals into an explicit operating boundary.",
      "It should reflect behavior users care about rather than an arbitrary perfect target.",
      "Missing the objective consumes error budget and can change release or incident priorities.",
      "The service targets 99.9 percent successful generations over each rolling 30-day period.",
    ),
    "Error budget": card(
      "An error budget is the amount of unreliability permitted while a service still meets its objective.",
      "A 99.9 percent success SLO allows 0.1 percent unsuccessful requests in its window.",
      "The budget can be spent quickly during an outage or gradually through small regressions.",
      "Budget policy helps balance reliability work against feature delivery.",
      "With one million monthly requests and a 99.9 percent SLO, roughly one thousand failures consume the full budget.",
    ),
    "Burn rate": card(
      "Burn rate measures how quickly the current error rate consumes an SLO error budget relative to its planned pace.",
      "A burn rate of one exhausts the budget exactly at the end of the objective window.",
      "A high burn rate can justify rapid paging even before the budget is fully gone.",
      "Combining short and long alert windows improves precision while catching active incidents.",
      "At a burn rate of ten, a 30-day error budget would be exhausted in about three days if conditions persist.",
    ),
    "Distributed trace": card(
      "A distributed trace is a connected set of timed spans representing one operation across components and boundaries.",
      "A root span represents the overall request while child spans represent queue, prefill, decode, or transport work.",
      "Span events can record notable moments without creating a separate timing interval.",
      "Every created span must be ended so telemetry and resources do not remain open indefinitely.",
      "One trace follows a chat request from the browser adapter through worker prefill, token decode, and final cleanup.",
    ),
    "OpenTelemetry span": card(
      "An OpenTelemetry span is a timed record of one unit of work and is the basic building block of a trace.",
      "Its core fields include a name, start and end timestamps, and span context containing trace and span identifiers.",
      "Attributes describe the operation, events mark notable moments, and status records the operation’s outcome.",
      "A parent span ID or span link relates the work to other operations, while ending the span closes its measured interval.",
      "A model.prefill span starts when prompt processing begins, records input_tokens=640, and ends when first-token scores are ready.",
    ),
    "Trace sampling": card(
      "Trace sampling is a policy for choosing which traces are processed and exported so telemetry volume remains affordable and useful.",
      "Head sampling decides early from information available near trace creation, making it efficient but unable to inspect the completed trace.",
      "Tail sampling considers most or all finished spans, so it can favor errors or slow traces but needs buffering and state.",
      "Parent-aware decisions propagate the sampled flag across services so one distributed trace does not become an accidental patchwork.",
      "A collector exports every completed trace containing an error and a 5 percent sample of the remaining healthy traces.",
    ),
    "Span context propagation": card(
      "Span context propagation carries trace identity and flags into downstream work so its spans join the same trace.",
      "SpanContext contains an immutable TraceId, SpanId, TraceFlags, and TraceState.",
      "A child span keeps the parent TraceId but receives its own SpanId.",
      "A remote-parent flag records that context crossed a process or transport boundary.",
      "A worker message carries trace context so its prefill span appears under the browser request span.",
    ),
  },
);

const conversationState = defineFlashcardGroup(
  {
    subjectId: "chat-integration",
    module: "Chat Integration",
    lesson: "Conversation State",
    source: "React official guides: Extracting State Logic into a Reducer, Choosing the State Structure, and Preserving and Resetting State.",
  },
  {
    "Chat state machine": card(
      "A chat state machine defines the allowed lifecycle states and event-driven transitions for conversations and generation.",
      "Queued, streaming, complete, cancelled, and error have different permitted actions.",
      "An explicit transition table prevents impossible combinations of flags.",
      "Transport events are inputs to the machine rather than direct uncontrolled mutations.",
      "A STOP action moves a streaming attempt to cancelled, while a late TOKEN action leaves it cancelled.",
    ),
    "Entity table": card(
      "An entity table stores each record once under a stable ID instead of nesting duplicate copies throughout state.",
      "A messagesById object makes direct message lookup predictable.",
      "Relationships point to IDs, so updating one record cannot leave a duplicate stale copy.",
      "Flat records are easier to replace immutably than deeply nested conversation objects.",
      "messagesById['m-7'] changes once while every conversation that references m-7 sees the same new record.",
    ),
    "Ordered ID list": card(
      "An ordered ID list represents display or conversation order while the actual records remain in an entity table.",
      "The list contains stable IDs rather than duplicate message objects.",
      "Reordering changes the ID sequence without rewriting message content.",
      "Rendering resolves each ID through the corresponding lookup table.",
      "messageIds ['u-1', 'a-1', 'u-2'] renders those three records in order from messagesById.",
    ),
    Reducer: card(
      "A reducer is a function that receives current state and an action and returns the next state.",
      "It centralizes related update rules that would otherwise be scattered across event handlers.",
      "Action types describe what happened, while the reducer decides how state changes.",
      "A reducer can be tested with fixed input state without rendering a component.",
      "chatReducer(state, {type: 'TOKEN_DELTA', messageId: 'a-1', delta: 'hi'}) returns the updated state.",
    ),
    "Action dispatch": card(
      "Action dispatch sends a descriptive event object to a reducer instead of directly editing application state.",
      "The action normally has a type plus only the data needed for that event.",
      "Names should describe what occurred, such as generation_cancelled, rather than a setter instruction.",
      "A chronological action log can explain how the current state was reached.",
      "The Stop button dispatches {type: 'GENERATION_CANCELLED', attemptId: 'a-4'} to the chat reducer.",
    ),
    "Pure reducer": card(
      "A pure reducer returns the same next state for the same state and action without causing outside effects.",
      "It must not fetch data, schedule timers, write storage, or post worker messages.",
      "It must not mutate its input objects or arrays.",
      "Effects observe resulting state or actions and perform external work separately.",
      "Running the same TOKEN_DELTA input twice in isolated tests produces identical output objects and no network calls.",
    ),
    "Immutable update": card(
      "An immutable update creates new values for changed state instead of modifying the previous snapshot in place.",
      "React can detect changes by comparing object identities.",
      "Earlier snapshots stay trustworthy for debugging and concurrent rendering.",
      "A no-match guard may preserve records while still returning the documented container shape.",
      "Appending “lo” replaces message a-1 with a new {content: 'Hello'} object and leaves the old {content: 'Hel'} untouched.",
    ),
    "Structural sharing": card(
      "Structural sharing reuses unchanged records inside a newly created immutable state container.",
      "Only the targeted message and its ancestor containers need new object identities.",
      "Untouched message objects remain referentially equal to their prior versions.",
      "Sharing reduces copying while preserving immutable-update guarantees.",
      "Updating the second of 100 messages creates one new message object while the other 99 objects are reused.",
    ),
    "Derived state": card(
      "Derived state is calculated from authoritative records during rendering instead of stored as another independent fact.",
      "canStop follows whether the active attempt is in a cancellable phase such as queued, loading, prefill, or streaming.",
      "canRegenerate follows whether an assistant attempt has reached an eligible terminal state.",
      "Calculating these values prevents saved booleans from contradicting lifecycle records.",
      "When an attempt changes from prefill to cancelled, canStop becomes false without dispatching a separate flag action.",
    ),
    "Single source of truth": card(
      "A single source of truth keeps each fact in one authoritative state location so copies cannot drift apart.",
      "Store selectedMessageId instead of duplicating the entire selected message.",
      "Compute status labels from the lifecycle phase rather than saving both independently.",
      "Duplicate state creates extra update paths and contradictory combinations.",
      "The UI looks up the selected message by ID, so editing its entity-table record updates every view consistently.",
    ),
    "Stable identity": card(
      "Stable identity names a record independently from its current position, visible text, or render count.",
      "Array indexes change when earlier messages are inserted or removed.",
      "Content is unsuitable as identity because edits and duplicate text are valid.",
      "Transport events should target stable IDs established before streaming begins.",
      "Message m-a7 remains m-a7 after an earlier system notice is inserted at index zero.",
    ),
    "React key and component identity": card(
      "A React key helps React decide whether a rendered component is the same identity or a new one at a position.",
      "Keys are useful beyond lists when state should follow a specific record.",
      "Changing a key intentionally resets that component’s local state.",
      "Reusing an index key can attach composer or message state to the wrong item after reordering.",
      "Using message.id as the key keeps the correct message component state when another message is inserted above it.",
    ),
  },
);

const streamingReact = defineFlashcardGroup(
  {
    subjectId: "chat-integration",
    module: "Chat Integration",
    lesson: "Streaming React",
    source: "MDN Using readable streams; WHATWG Streams Standard; React official useTransition and state queueing guides.",
  },
  {
    "Transport-render boundary": card(
      "The transport-render boundary separates protocol consumption from the state updates and policies used to draw the interface.",
      "The transport side owns bytes, decoding, frames, and typed events.",
      "The React side receives validated events and decides when to render them.",
      "A rendering pause must not silently redefine network or cancellation behavior.",
      "The adapter emits a token delta, and only then does the UI place that delta into its next-frame render queue.",
    ),
    "Token delta": card(
      "A token delta is the exact incremental text fragment delivered for an in-progress assistant message.",
      "A delta may contain a subword, whitespace, punctuation, Unicode, or an empty string.",
      "Joining deltas must preserve their original arrival order.",
      "The UI should not insert separators because spacing is already part of the fragments.",
      "The ordered deltas ['A', ' causal', ' model'] combine exactly into “A causal model”.",
    ),
    "Pending render queue": card(
      "A pending render queue holds token deltas that arrived after the last screen update and await the next flush.",
      "The queue is a UI scheduling structure, not an SSE frame buffer.",
      "It retains the exact text and order of every accepted delta.",
      "Completion and cancellation need explicit, different rules for queued text.",
      "Three deltas arriving at 2, 7, and 11 ms wait together until the 16 ms animation-frame callback.",
    ),
    requestAnimationFrame: card(
      "requestAnimationFrame schedules a callback before a browser paint so visual work can align with the display cycle.",
      "Several deltas can accumulate before one scheduled callback runs.",
      "Only one pending callback is needed for a given render queue.",
      "The returned handle can be cancelled when the generation stops.",
      "Five token events arrive during one frame, and a single requestAnimationFrame callback flushes all five before paint.",
    ),
    "Frame coalescing": card(
      "Frame coalescing combines multiple accepted stream events into one visual update during an animation-frame interval.",
      "It reduces render and layout frequency without changing delivered text.",
      "Bursty streams usually combine more deltas per commit than slow streams.",
      "Coalescing concerns display cadence and does not authorize dropping protocol events.",
      "Eight deltas arriving within 14 ms become one reducer action and one screen commit at the next frame.",
    ),
    "Reducer batch action": card(
      "A reducer batch action applies the joined contents of one render flush through a single state transition.",
      "The action still includes stable message, attempt, and request identity.",
      "One batch preserves the same text result as dispatching its deltas individually in order.",
      "Late or mismatched batch actions must pass the same guards as single-token events.",
      "TOKEN_BATCH for a-2 carries “Hello world” and updates the active assistant message once.",
    ),
    "React state batching": card(
      "React state batching groups queued updates so the interface avoids rendering incomplete intermediate combinations.",
      "Updates made during one handled event are commonly processed together.",
      "Updater functions receive the latest queued value when several changes depend on one another.",
      "Separate intentional user events are not treated as one indistinguishable action.",
      "Three queued count updaters can produce one render showing the final value rather than three half-finished screens.",
    ),
    "React transition": card(
      "A React transition marks a state update as non-urgent so more immediate input can interrupt its rendering work.",
      "useTransition returns an isPending flag and a startTransition function.",
      "A transition may be restarted if an urgent update arrives during rendering.",
      "Controlled text-input state itself should remain synchronous rather than transition-driven.",
      "Switching a heavy transcript view runs in a transition while typing in the composer remains immediate.",
    ),
    "Interruptible rendering": card(
      "Interruptible rendering lets React abandon unfinished non-urgent render work and restart it with the newest state.",
      "Abandoned render work never commits a half-finished version of the document object model.",
      "An urgent update can preempt a transition or deferred render without using a separate JavaScript thread.",
      "Restarted work uses current props and state, and its effects run only after a successful commit.",
      "React abandons an old transcript-filter render for a keystroke, then restarts the filter with the latest query.",
    ),
    "Near-bottom threshold": card(
      "A near-bottom threshold defines how close a reader must be to the scroll end before new content follows automatically.",
      "The distance equals scroll height minus scroll position minus viewport height.",
      "A small tolerance absorbs font and layout changes around the exact bottom.",
      "An explicit user-scrolled-up flag should override distance alone.",
      "At 24 pixels from the bottom with an 80-pixel threshold, the view follows unless the reader opted out.",
    ),
    "Announcement batching": card(
      "Announcement batching groups streaming text into meaningful accessibility updates instead of speaking every small token delta.",
      "Token-by-token announcements can overwhelm assistive-technology users.",
      "Batches should retain useful reading order and understandable phrase boundaries.",
      "Completion gets one clear final announcement after any pending text is handled.",
      "The UI announces “The model finished its answer” once rather than speaking 60 separate token fragments.",
    ),
    "Cancellation cleanup": card(
      "Cancellation cleanup stops scheduled UI work and releases transport resources when a generation is deliberately ended.",
      "The animation-frame callback is cancelled so queued text cannot appear afterward.",
      "The reader or generator is aborted rather than merely hidden from view.",
      "Late events are rejected and the committed partial response receives an honest cancelled status.",
      "Pressing Stop drops the pending phrase “ positions.”, cancels the reader, and keeps the already shown partial answer.",
    ),
  },
);

const actionsAndContext = defineFlashcardGroup(
  {
    subjectId: "chat-integration",
    module: "Chat Integration",
    lesson: "Actions and Context",
    source: "OpenAI Conversation state guide; MDN AbortController; React Queueing a Series of State Updates.",
  },
  {
    "Conversation graph": card(
      "A conversation graph represents messages and generation attempts as branching records rather than one overwriteable text list.",
      "A user message can be the parent of several regenerated assistant attempts.",
      "Editing creates a new branch while preserving the old branch for history or comparison.",
      "Graph relationships make ancestry explicit through stable IDs.",
      "User message u-3 has assistant children a-31 and a-32, while edited u-3-e1 starts a separate child a-33.",
    ),
    "Active branch prefix": card(
      "An active branch prefix is the ordered chain of conversation records leading to the prompt currently being answered.",
      "Only records on the selected branch are eligible for its model context.",
      "Old branches remain stored but do not silently reenter a new request.",
      "The prefix ends at the current user message before its new assistant attempt.",
      "The edited branch uses system s-1, user u-1, assistant a-1, and edited user u-3-e1 as its active prefix.",
    ),
    "Descendant invalidation": card(
      "Descendant invalidation marks responses based on an older edited record as inapplicable to the new branch.",
      "Invalidation preserves audit history instead of deleting prior messages.",
      "Only descendants of the changed branch point are excluded.",
      "Unrelated earlier completed turns can remain eligible context.",
      "Editing u-3 invalidates its assistant child a-3 for the new branch but leaves the earlier u-1 and a-1 turn valid.",
    ),
    Regeneration: card(
      "Regeneration creates a new assistant attempt from the same parent user message without rewriting the earlier attempt.",
      "The new attempt and transport run receive fresh identities.",
      "Model, prompt, and sampling settings should be recorded for the new try.",
      "The earlier output remains available with its own terminal status.",
      "Regenerate keeps parent u-4 but creates assistant m-a9, attempt a-2, and transport request r-2.",
    ),
    "Stopped partial output": card(
      "Stopped partial output is text already shown before cancellation and retained with an honest cancelled status.",
      "Stopping should abort the active transport and generation work.",
      "Visible partial text is not relabeled as complete.",
      "A later retry creates another attempt instead of appending onto the cancelled one.",
      "After “Set future logits” appears, Stop preserves those words on cancelled attempt a-31 and releases its reader.",
    ),
    "Conversation object": card(
      "A conversation object is a durable API-side container that can persist related items across requests and sessions.",
      "Stored items may include messages, tool calls, tool outputs, and other response records.",
      "The object has its own stable identifier that later API requests can reference.",
      "Durable provider state is separate from the local UI’s normalized records.",
      "A mobile session and a later desktop job both continue conversation conv_42 by referring to the same object.",
    ),
    previous_response_id: card(
      "previous_response_id links a new model response to an earlier response so the provider can continue that chain’s state.",
      "The identifier names a prior response rather than the entire local conversation record.",
      "Earlier input tokens in the chain can still count toward billing and context use.",
      "In Responses WebSocket mode, an uncached prior ID may require previous_response_id null plus the full input context.",
      "A follow-up asks “why?” with previous_response_id set to resp_17 instead of manually copying resp_17’s output.",
    ),
    "Request context allocation": card(
      "Request context allocation divides a model’s finite context capacity among input, visible output, and reasoning tokens where applicable.",
      "System instructions, history, tool records, and the current prompt consume the input allocation.",
      "Reserve expected visible output and reasoning tokens before filling the remaining space with optional history.",
      "Durable conversation storage does not mean every stored item fits into one model request.",
      "A 4,096-token capacity reserving 800 output and 300 reasoning tokens leaves at most 2,996 tokens for input.",
    ),
    "Token budget": card(
      "A token budget is the explicit maximum amount of context space assigned to a request or selection step.",
      "Required inputs consume budget before optional historical turns are considered.",
      "Token counts should come from the target model’s tokenizer when production accuracy matters.",
      "The selector reports exact used tokens rather than assuming selected message count predicts size.",
      "With a budget of 26, six required tokens leave 20 tokens available for complete historical turns.",
    ),
    "Context projection": card(
      "Context projection builds one model request from the active branch and budget without changing the durable conversation graph.",
      "Required instructions and the active user prompt are always included.",
      "Eligible history is considered newest first but emitted in chronological order.",
      "A large skipped turn does not prevent a smaller older complete turn from fitting.",
      "The graph stores 40 messages, while the projected request sends s-1, u-7, a-7, and current u-9 only.",
    ),
    "Atomic turn": card(
      "An atomic turn is a completed user-assistant pair admitted to or removed from historical context as one unit.",
      "Streaming, cancelled, error, and orphan assistant records are not complete historical turns.",
      "Keeping pairs intact prevents the model from seeing an answer without its question.",
      "Selected pairs retain their original user-before-assistant order.",
      "If u-2 and a-2 need eight tokens together, a six-token remainder includes neither record rather than only u-2.",
    ),
    "Required-prefix overflow": card(
      "Required-prefix overflow occurs when mandatory instructions and the active prompt already exceed the available token budget.",
      "The required records remain identified instead of being silently truncated by history policy.",
      "An overflow flag tells the caller not to send the request unchanged.",
      "Removing optional history cannot solve an overflow caused entirely by mandatory input.",
      "System instructions use 18 tokens and the active prompt 12 under a 24-token budget, so overflow is true at 30.",
    ),
    "Replay metadata": card(
      "Replay metadata records the settings and identities needed to explain why two generation attempts may differ.",
      "Useful fields include model ID, prompt version, temperature, and top-p.",
      "Included message IDs preserve the exact context projection used by the attempt.",
      "Attempt and request IDs connect the record to transport events and telemetry.",
      "Attempt a-33 records model local-135m, prompt chat-v3, temperature 0.7, top-p 0.9, and four context IDs.",
    ),
  },
);

const productQuality = defineFlashcardGroup(
  {
    subjectId: "chat-integration",
    module: "Chat Integration",
    lesson: "Product Quality",
    source: "W3C WCAG 2.2 ARIA23 and Status Messages guidance; web.dev Interaction to Next Paint; course-authored Product Quality storage-validation contract.",
  },
  {
    "Generation lifecycle phase": card(
      "A generation lifecycle phase is the explicit current state used to coordinate status text, controls, and cleanup.",
      "Queued, loading, prefill, and streaming represent distinct active work.",
      "Complete, cancelled, and error are terminal phases that reject later events.",
      "The visible label should map directly from this state rather than from unrelated loading flags.",
      "Phase prefill displays “Processing context” and enables Stop without pretending that tokens are already streaming.",
    ),
    "Persistence boundary": card(
      "A persistence boundary controls exactly what live application state may be serialized and later restored.",
      "Transient readers, controllers, promises, and streaming buffers stay outside saved data.",
      "Serialization converts rich reducer state into a smaller durable record.",
      "Restoration validates the record before reconstructing safe UI defaults.",
      "The app saves final message text and IDs but never saves the active AbortController or pending render queue.",
    ),
    "Schema version": card(
      "A schema version identifies the exact saved-record format so compatibility can be checked during restoration.",
      "The version belongs inside the persisted record rather than only in application code.",
      "Unknown future versions should be rejected until a supported migration exists.",
      "A migration changes old safe data deliberately instead of guessing field meaning.",
      "Version 1 stores terminal messages; a version 2 loader either migrates v1 explicitly or reports it unsupported.",
    ),
    "Untrusted saved data": card(
      "Untrusted saved data is persisted content treated as outside input when it returns to the application.",
      "Browser storage can be manually edited, corrupted, or left by an older application version.",
      "Every nested message must be checked rather than trusting a valid top-level object.",
      "Validation occurs before restored data reaches reducer state or rendering.",
      "A local record with a nested providerKey is rejected even though the app originally created the storage entry.",
    ),
    "Exact-key allowlist": card(
      "An exact-key allowlist accepts only documented fields and rejects extra properties at every validated object level.",
      "Required keys must all be present and optional keys must come from a small known set.",
      "Extra fields can leak secrets or smuggle unsupported lifecycle state.",
      "Object spreading caller input is unsafe at a strict persistence boundary.",
      "A message with id, role, backend, content, and status passes, while adding apiKey makes the same record fail.",
    ),
    "Fail-closed validation": card(
      "Fail-closed validation rejects malformed or unknown data instead of interpreting it with permissive defaults.",
      "Unknown roles, backends, statuses, and versions are invalid.",
      "Blank or excessively long identifiers fail the same boundary.",
      "A validation exception returns a safe failure rather than partially restoring the record.",
      "A future status named paused is rejected by today’s loader instead of being silently treated as complete.",
    ),
    "Terminal-only restoration": card(
      "Terminal-only restoration loads messages whose requests already ended and never resumes a saved in-progress stream.",
      "Complete, cancelled, and error are safe terminal statuses in this contract.",
      "Queued, loading, prefill, and streaming records depend on resources that disappeared during reload.",
      "A cancelled partial response may be restored as historical text with its honest status.",
      "After refresh, a complete answer reappears, while a saved streaming record is discarded instead of shown as active.",
    ),
    "Payload size bound": card(
      "A payload size bound limits record count and text length before persisted conversation data is accepted.",
      "Per-message limits stop one record from containing unbounded content.",
      "A total-content limit catches many individually valid messages that are excessive together.",
      "Message-count limits control traversal, rendering, and storage cost.",
      "The loader accepts up to 200 messages and 200,000 total characters but rejects the 201st message.",
    ),
    "role=log": card(
      "The Accessible Rich Internet Applications (ARIA) role log identifies a region where new items are appended in meaningful sequential order.",
      "Chat history is a standard use because new messages appear at the end of an ordered conversation.",
      "Assistive technology may announce additions without moving keyboard focus into the log.",
      "The region needs an accessible label so users know what sequence it represents.",
      "A div labeled “Chat history” uses role=log, and a screen reader announces each newly appended message.",
    ),
    "ARIA live region": card(
      "An Accessible Rich Internet Applications (ARIA) live region exposes changing page content so assistive technology can announce it without a focus change.",
      "Polite updates wait for a suitable pause, while assertive updates interrupt more readily.",
      "aria-atomic controls whether the full region or only changed content is presented.",
      "Overly frequent writes can make an otherwise correct interface exhausting to use.",
      "A polite status region announces “Generation complete” once after the final token is committed.",
    ),
    "WCAG status message": card(
      "A Web Content Accessibility Guidelines (WCAG) status message reports progress, results, success, or errors without taking focus or causing a page change.",
      "Success Criterion 4.1.3 requires displayed status information to be programmatically identifiable.",
      "Appropriate roles let assistive technology present the update at the right time.",
      "A dialog that takes focus is a change of context rather than this kind of status message.",
      "After Send, “Waiting for capacity” updates in a status region while focus remains in the conversation controls.",
    ),
    "Focus management": card(
      "Focus management deliberately moves or preserves keyboard focus after an interface state change so the next action is predictable.",
      "Cancellation should not leave focus on a Stop button that disappears.",
      "Recovery commonly returns focus to the composer or a clearly labeled Retry control.",
      "Automated DOM checks cannot fully prove useful screen-reader or keyboard focus behavior.",
      "When Stop completes, focus returns to the composer and the retained partial answer remains available in the log.",
    ),
    "Interaction to Next Paint (INP)": card(
      "Interaction to Next Paint summarizes a page visit’s overall responsiveness using its slowest qualifying interaction, with outlier handling on highly interactive pages.",
      "Each interaction latency includes input delay, event-handler processing, and presentation delay.",
      "A visit’s INP uses its worst or near-worst qualifying click, tap, or keyboard interaction rather than an average.",
      "Field reporting evaluates the 75th percentile of page visits and separates mobile from desktop.",
      "A visit with 80, 150, and 110 millisecond interaction latencies has an INP of 150 milliseconds when no outlier is discarded.",
    ),
  },
);

export const systemsAndProductExpansionLibrary = combineFlashcardLibraries(
  inferenceMechanics,
  schedulingAndMemory,
  streamingTransport,
  reliabilityAndObservability,
  conversationState,
  streamingReact,
  actionsAndContext,
  productQuality,
);
