import type { LessonSource } from "@latent/course-kit";

export const lessonSources: Record<string, LessonSource[]> = {
  "character-rnns": [
    {
      role: "Primary",
      title: "The Unreasonable Effectiveness of Recurrent Neural Networks",
      authors: "Andrej Karpathy",
      year: "2015",
      url: "https://karpathy.github.io/2015/05/21/rnn-effectiveness/",
      relevance: "Character-level prediction, recurrent state, sampling, and the original qualitative demonstrations.",
    },
    {
      role: "Implementation",
      title: "char-rnn",
      authors: "Andrej Karpathy",
      year: "2015",
      url: "https://github.com/karpathy/char-rnn",
      relevance: "The multi-layer Torch implementation used to produce the essay's character-model experiments.",
    },
    {
      role: "Paper",
      title: "Long Short-Term Memory",
      authors: "Sepp Hochreiter · Jürgen Schmidhuber",
      year: "1997",
      url: "https://direct.mit.edu/neco/article/9/8/1735/6109/Long-Short-Term-Memory",
      relevance: "Explains the gated recurrent architecture and error-flow problem behind the essay's LSTM results.",
    },
  ],
  "neural-language-models": [
    {
      role: "Primary",
      title: "A Neural Probabilistic Language Model",
      authors: "Yoshua Bengio et al.",
      year: "2003",
      url: "https://www.jmlr.org/papers/v3/bengio03a.html",
      relevance: "Introduces jointly learned distributed word representations inside a neural language model.",
    },
    {
      role: "Paper",
      title: "Efficient Estimation of Word Representations in Vector Space",
      authors: "Tomas Mikolov et al.",
      year: "2013",
      url: "https://arxiv.org/abs/1301.3781",
      relevance: "Shows how simpler objectives make high-quality distributed word representations practical at scale.",
    },
    {
      role: "Paper",
      title: "Distributed Representations of Words and Phrases",
      authors: "Tomas Mikolov et al.",
      year: "2013",
      url: "https://papers.nips.cc/paper/2013/hash/9aa42b31882ec039965f3c4923ce901b-Abstract.html",
      relevance: "Adds negative sampling, subsampling, and phrase representations to the embedding lineage.",
    },
  ],
  "subword-tokenization": [
    {
      role: "Primary",
      title: "Neural Machine Translation of Rare Words with Subword Units",
      authors: "Rico Sennrich · Barry Haddow · Alexandra Birch",
      year: "2016",
      url: "https://aclanthology.org/P16-1162/",
      relevance: "Applies byte-pair encoding to open-vocabulary neural sequence modeling.",
    },
    {
      role: "Paper",
      title: "SentencePiece",
      authors: "Taku Kudo · John Richardson",
      year: "2018",
      url: "https://arxiv.org/abs/1808.06226",
      relevance: "Extends subword training to raw sentences with a language-independent tokenizer and detokenizer.",
    },
    {
      role: "Implementation",
      title: "SentencePiece reference implementation",
      authors: "Google",
      year: "Current",
      url: "https://github.com/google/sentencepiece",
      relevance: "Production implementation of BPE and unigram tokenization with reproducible model artifacts.",
    },
  ],
  "additive-attention": [
    {
      role: "Primary",
      title: "Neural Machine Translation by Jointly Learning to Align and Translate",
      authors: "Dzmitry Bahdanau · Kyunghyun Cho · Yoshua Bengio",
      year: "2014",
      url: "https://arxiv.org/abs/1409.0473",
      relevance: "Introduces learned soft alignment that removes the fixed-vector encoder bottleneck.",
    },
    {
      role: "Paper",
      title: "Effective Approaches to Attention-based Neural Machine Translation",
      authors: "Minh-Thang Luong · Hieu Pham · Christopher Manning",
      year: "2015",
      url: "https://aclanthology.org/D15-1166/",
      relevance: "Compares global and local attention plus alternative alignment scoring functions.",
    },
    {
      role: "Paper",
      title: "Show, Attend and Tell",
      authors: "Kelvin Xu et al.",
      year: "2015",
      url: "https://arxiv.org/abs/1502.03044",
      relevance: "Demonstrates soft and hard visual attention in an image-captioning sequence model.",
    },
  ],
  transformers: [
    {
      role: "Primary",
      title: "Attention Is All You Need",
      authors: "Ashish Vaswani et al.",
      year: "2017",
      url: "https://papers.nips.cc/paper_files/paper/2017/hash/3f5ee243547dee91fbd053c1c4a845aa-Abstract.html",
      relevance: "Defines the Transformer architecture, multi-head attention, positional encoding, and residual blocks.",
    },
    {
      role: "Implementation",
      title: "The Annotated Transformer",
      authors: "Harvard NLP",
      year: "2018",
      url: "https://nlp.seas.harvard.edu/annotated-transformer/",
      relevance: "A line-by-line implementation that connects the paper's equations to working modules.",
    },
    {
      role: "Paper",
      title: "Improving Language Understanding by Generative Pre-Training",
      authors: "Alec Radford et al.",
      year: "2018",
      url: "https://cdn.openai.com/research-covers/language-unsupervised/language_understanding_paper.pdf",
      relevance: "Adapts a masked decoder-only Transformer to generative language-model pretraining and transfer.",
    },
  ],
  "in-context-learning": [
    {
      role: "Primary",
      title: "Language Models are Few-Shot Learners",
      authors: "Tom Brown et al.",
      year: "2020",
      url: "https://arxiv.org/abs/2005.14165",
      relevance: "Establishes the modern zero-, one-, and few-shot evaluation framing for scaled autoregressive models.",
    },
    {
      role: "Paper",
      title: "Rethinking the Role of Demonstrations",
      authors: "Sewon Min et al.",
      year: "2022",
      url: "https://aclanthology.org/2022.emnlp-main.759/",
      relevance: "Tests which properties of prompt demonstrations actually drive classification performance.",
    },
    {
      role: "Paper",
      title: "What Can Transformers Learn In-Context?",
      authors: "Shivam Garg et al.",
      year: "2022",
      url: "https://arxiv.org/abs/2208.01066",
      relevance: "Studies in-context learning as an executable learning algorithm on controlled function classes.",
    },
  ],
  "inference-runtime": [
    {
      role: "Primary",
      title: "Efficient Memory Management for Large Language Model Serving with PagedAttention",
      authors: "Woosuk Kwon et al.",
      year: "2023",
      url: "https://arxiv.org/abs/2309.06180",
      relevance: "Connects KV-cache allocation, request concurrency, and serving throughput through paged memory.",
    },
    {
      role: "Paper",
      title: "FlashAttention",
      authors: "Tri Dao et al.",
      year: "2022",
      url: "https://papers.nips.cc/paper_files/paper/2022/hash/67d57c32e20fd0a7a302cb81d36e40d5-Abstract-Conference.html",
      relevance: "Explains why attention performance depends on memory traffic and IO-aware kernel design.",
    },
    {
      role: "Guide",
      title: "Cache strategies",
      authors: "Hugging Face Transformers",
      year: "Current",
      url: "https://huggingface.co/docs/transformers/kv_cache",
      relevance: "Documents concrete KV-cache policies, offloading, quantization, and compile-time tradeoffs.",
    },
  ],
  "streaming-transport": [
    {
      role: "Primary",
      title: "Server-sent events",
      authors: "WHATWG HTML Standard",
      year: "Living standard",
      url: "https://html.spec.whatwg.org/multipage/server-sent-events.html",
      relevance: "Normative event-stream framing, parsing, identifiers, reconnection, and UTF-8 behavior.",
    },
    {
      role: "Specification",
      title: "Streams Standard",
      authors: "WHATWG",
      year: "Living standard",
      url: "https://streams.spec.whatwg.org/",
      relevance: "Defines readable streams, readers, queues, cancellation, and backpressure semantics.",
    },
    {
      role: "Guide",
      title: "Using server-sent events",
      authors: "MDN Web Docs",
      year: "Current",
      url: "https://developer.mozilla.org/en-US/docs/Web/API/Server-sent_events/Using_server-sent_events",
      relevance: "Practical browser and server examples for event names, data fields, errors, and connection limits.",
    },
  ],
  "scheduling-memory": [
    {
      role: "Primary",
      title: "Orca: A Distributed Serving System for Transformer-Based Generative Models",
      authors: "Gyeong-In Yu et al.",
      year: "2022",
      url: "https://www.usenix.org/conference/osdi22/presentation/yu",
      relevance: "Introduces iteration-level scheduling and selective batching for autoregressive serving.",
    },
    {
      role: "Paper",
      title: "PagedAttention and vLLM",
      authors: "Woosuk Kwon et al.",
      year: "2023",
      url: "https://arxiv.org/abs/2309.06180",
      relevance: "Shows how memory allocation and continuous batching interact under variable-length requests.",
    },
    {
      role: "Paper",
      title: "Taming Throughput-Latency Tradeoff with Sarathi-Serve",
      authors: "Amey Agrawal et al.",
      year: "2024",
      url: "https://arxiv.org/abs/2403.02310",
      relevance: "Adds chunked prefills and stall-free schedules to balance throughput with token latency.",
    },
  ],
  "reliability-observability": [
    {
      role: "Primary",
      title: "Monitoring Distributed Systems",
      authors: "Google SRE",
      year: "2016",
      url: "https://sre.google/sre-book/monitoring-distributed-systems/",
      relevance: "Defines latency, traffic, errors, and saturation as user-centered monitoring signals.",
    },
    {
      role: "Guide",
      title: "Alerting on SLOs",
      authors: "Google SRE Workbook",
      year: "2018",
      url: "https://sre.google/workbook/alerting-on-slos/",
      relevance: "Turns error budgets and burn rates into actionable multi-window alerts.",
    },
    {
      role: "Specification",
      title: "OpenTelemetry Trace specification",
      authors: "OpenTelemetry",
      year: "Current",
      url: "https://opentelemetry.io/docs/specs/otel/trace/",
      relevance: "Defines spans, context, events, status, sampling, and export boundaries for distributed traces.",
    },
  ],
  "conversation-state": [
    {
      role: "Primary",
      title: "Extracting State Logic into a Reducer",
      authors: "React",
      year: "Current",
      url: "https://react.dev/learn/extracting-state-logic-into-a-reducer",
      relevance: "Establishes pure reducers and action-driven state transitions for complex UI behavior.",
    },
    {
      role: "Guide",
      title: "Choosing the State Structure",
      authors: "React",
      year: "Current",
      url: "https://react.dev/learn/choosing-the-state-structure",
      relevance: "Covers normalization, derived state, contradiction avoidance, and stable identifiers.",
    },
    {
      role: "Guide",
      title: "Preserving and Resetting State",
      authors: "React",
      year: "Current",
      url: "https://react.dev/learn/preserving-and-resetting-state",
      relevance: "Explains how component identity and keys determine whether conversation UI state survives a render.",
    },
  ],
  "streaming-react": [
    {
      role: "Primary",
      title: "Using readable streams",
      authors: "MDN Web Docs",
      year: "Current",
      url: "https://developer.mozilla.org/en-US/docs/Web/API/Streams_API/Using_readable_streams",
      relevance: "Practical asynchronous consumption, cancellation, and custom stream construction in the browser.",
    },
    {
      role: "Specification",
      title: "Streams Standard",
      authors: "WHATWG",
      year: "Living standard",
      url: "https://streams.spec.whatwg.org/",
      relevance: "Normative behavior for chunks, readers, queues, cancellation, and backpressure.",
    },
    {
      role: "Guide",
      title: "useTransition",
      authors: "React",
      year: "Current",
      url: "https://react.dev/reference/react/useTransition",
      relevance: "Clarifies how non-blocking render work can preserve responsiveness during frequent updates.",
    },
  ],
  "chat-actions-context": [
    {
      role: "Primary",
      title: "Conversation state",
      authors: "OpenAI API documentation",
      year: "Current",
      url: "https://developers.openai.com/api/docs/guides/conversation-state",
      relevance: "Describes explicit conversation continuity across independent model requests.",
    },
    {
      role: "Guide",
      title: "AbortController",
      authors: "MDN Web Docs",
      year: "Current",
      url: "https://developer.mozilla.org/en-US/docs/Web/API/AbortController",
      relevance: "Defines the browser cancellation primitive used to stop fetches, streams, and generation work.",
    },
    {
      role: "Guide",
      title: "Queueing a Series of State Updates",
      authors: "React",
      year: "Current",
      url: "https://react.dev/learn/queueing-a-series-of-state-updates",
      relevance: "Explains queued state transitions and updater functions used by retry, edit, and streaming actions.",
    },
  ],
  "chat-product-quality": [
    {
      role: "Primary",
      title: "Log Pattern",
      authors: "W3C WAI-ARIA Authoring Practices",
      year: "Current",
      url: "https://www.w3.org/WAI/ARIA/apg/patterns/log/",
      relevance: "Defines an accessible container for sequential additions such as messages in a conversation.",
    },
    {
      role: "Specification",
      title: "Understanding Status Messages",
      authors: "W3C Web Accessibility Initiative",
      year: "WCAG 2.2",
      url: "https://www.w3.org/WAI/WCAG22/Understanding/status-messages",
      relevance: "Explains when progress, completion, and error updates must be programmatically announced.",
    },
    {
      role: "Guide",
      title: "Interaction to Next Paint",
      authors: "web.dev",
      year: "Current",
      url: "https://web.dev/articles/inp",
      relevance: "Provides the responsiveness metric needed to evaluate interaction and streaming-render latency.",
    },
  ],
};

export function getLessonSources(lessonId: string) {
  const sources = lessonSources[lessonId];
  if (!sources || sources.length < 2) throw new Error(`Lesson ${lessonId} requires multiple sources.`);
  return sources;
}
