import type { LessonSource } from "@latent/course-kit";

export const lessonSources: Record<string, LessonSource[]> = {
  "character-rnns": [
    {
      role: "Primary",
      title: "The Unreasonable Effectiveness of Recurrent Neural Networks",
      authors: "Andrej Karpathy",
      year: "2015",
      url: "https://karpathy.github.io/2015/05/21/rnn-effectiveness/",
      relevance: "Covers character-by-character prediction, recurrent state, sampling, and the original demos.",
    },
    {
      role: "Implementation",
      title: "char-rnn",
      authors: "Andrej Karpathy",
      year: "2015",
      url: "https://github.com/karpathy/char-rnn",
      relevance: "This is the multi-layer Torch code behind the essay's character-model experiments.",
    },
    {
      role: "Paper",
      title: "Long Short-Term Memory",
      authors: "Sepp Hochreiter · Jürgen Schmidhuber",
      year: "1997",
      url: "https://direct.mit.edu/neco/article/9/8/1735/6109/Long-Short-Term-Memory",
      relevance: "Explains the gated recurrent setup and the gradient problem behind the essay's LSTM results.",
    },
  ],
  "neural-language-models": [
    {
      role: "Primary",
      title: "A Neural Probabilistic Language Model",
      authors: "Yoshua Bengio et al.",
      year: "2003",
      url: "https://www.jmlr.org/papers/v3/bengio03a.html",
      relevance: "Shows how a neural language model can learn useful word embeddings while it trains.",
    },
    {
      role: "Paper",
      title: "Efficient Estimation of Word Representations in Vector Space",
      authors: "Tomas Mikolov et al.",
      year: "2013",
      url: "https://arxiv.org/abs/1301.3781",
      relevance: "Shows how simpler training goals make strong word embeddings practical at scale.",
    },
    {
      role: "Paper",
      title: "Distributed Representations of Words and Phrases",
      authors: "Tomas Mikolov et al.",
      year: "2013",
      url: "https://papers.nips.cc/paper/2013/hash/9aa42b31882ec039965f3c4923ce901b-Abstract.html",
      relevance: "Adds negative sampling, subsampling, and phrase embeddings to the approach.",
    },
  ],
  "subword-tokenization": [
    {
      role: "Primary",
      title: "Neural Machine Translation of Rare Words with Subword Units",
      authors: "Rico Sennrich · Barry Haddow · Alexandra Birch",
      year: "2016",
      url: "https://aclanthology.org/P16-1162/",
      relevance: "Shows how byte-pair encoding handles rare and unseen words in neural sequence models.",
    },
    {
      role: "Paper",
      title: "SentencePiece",
      authors: "Taku Kudo · John Richardson",
      year: "2018",
      url: "https://arxiv.org/abs/1808.06226",
      relevance: "Trains subword models straight from raw sentences, without language-specific tokenization rules.",
    },
    {
      role: "Implementation",
      title: "SentencePiece reference implementation",
      authors: "Google",
      year: "Current",
      url: "https://github.com/google/sentencepiece",
      relevance: "Provides production-ready BPE and unigram tokenization with reproducible model files.",
    },
  ],
  "additive-attention": [
    {
      role: "Primary",
      title: "Neural Machine Translation by Jointly Learning to Align and Translate",
      authors: "Dzmitry Bahdanau · Kyunghyun Cho · Yoshua Bengio",
      year: "2014",
      url: "https://arxiv.org/abs/1409.0473",
      relevance: "Introduces learned soft alignment so the encoder isn't squeezed into one fixed vector.",
    },
    {
      role: "Paper",
      title: "Effective Approaches to Attention-based Neural Machine Translation",
      authors: "Minh-Thang Luong · Hieu Pham · Christopher Manning",
      year: "2015",
      url: "https://aclanthology.org/D15-1166/",
      relevance: "Compares global and local attention along with several ways to score alignment.",
    },
    {
      role: "Paper",
      title: "Show, Attend and Tell",
      authors: "Kelvin Xu et al.",
      year: "2015",
      url: "https://arxiv.org/abs/1502.03044",
      relevance: "Shows soft and hard visual attention at work in an image-captioning model.",
    },
  ],
  transformers: [
    {
      role: "Primary",
      title: "Attention Is All You Need",
      authors: "Ashish Vaswani et al.",
      year: "2017",
      url: "https://papers.nips.cc/paper_files/paper/2017/hash/3f5ee243547dee91fbd053c1c4a845aa-Abstract.html",
      relevance: "Lays out the Transformer, including multi-head attention, positional encoding, and residual blocks.",
    },
    {
      role: "Implementation",
      title: "The Annotated Transformer",
      authors: "Harvard NLP",
      year: "2018",
      url: "https://nlp.seas.harvard.edu/annotated-transformer/",
      relevance: "Walks through the implementation line by line and turns the paper's equations into working modules.",
    },
    {
      role: "Paper",
      title: "Improving Language Understanding by Generative Pre-Training",
      authors: "Alec Radford et al.",
      year: "2018",
      url: "https://cdn.openai.com/research-covers/language-unsupervised/language_understanding_paper.pdf",
      relevance: "Uses a masked decoder-only Transformer for language-model pretraining and transfer learning.",
    },
  ],
  "in-context-learning": [
    {
      role: "Primary",
      title: "Language Models are Few-Shot Learners",
      authors: "Tom Brown et al.",
      year: "2020",
      url: "https://arxiv.org/abs/2005.14165",
      relevance: "Popularized the modern zero-, one-, and few-shot setup for large autoregressive models.",
    },
    {
      role: "Paper",
      title: "Rethinking the Role of Demonstrations",
      authors: "Sewon Min et al.",
      year: "2022",
      url: "https://aclanthology.org/2022.emnlp-main.759/",
      relevance: "Tests which parts of prompt examples actually help classification performance.",
    },
    {
      role: "Paper",
      title: "What Can Transformers Learn In-Context?",
      authors: "Shivam Garg et al.",
      year: "2022",
      url: "https://arxiv.org/abs/2208.01066",
      relevance: "Studies in-context learning as a learning algorithm using controlled function tasks.",
    },
  ],
  "inference-runtime": [
    {
      role: "Primary",
      title: "Efficient Memory Management for Large Language Model Serving with PagedAttention",
      authors: "Woosuk Kwon et al.",
      year: "2023",
      url: "https://arxiv.org/abs/2309.06180",
      relevance: "Shows how paged memory connects KV-cache allocation, concurrent requests, and serving throughput.",
    },
    {
      role: "Paper",
      title: "FlashAttention",
      authors: "Tri Dao et al.",
      year: "2022",
      url: "https://papers.nips.cc/paper_files/paper/2022/hash/67d57c32e20fd0a7a302cb81d36e40d5-Abstract-Conference.html",
      relevance: "Explains why attention speed depends so much on memory traffic and IO-aware kernels.",
    },
    {
      role: "Guide",
      title: "Cache strategies",
      authors: "Hugging Face Transformers",
      year: "Current",
      url: "https://huggingface.co/docs/transformers/kv_cache",
      relevance: "Covers real KV-cache options, including offloading, quantization, and compile-time tradeoffs.",
    },
  ],
  "streaming-transport": [
    {
      role: "Primary",
      title: "Server-sent events",
      authors: "WHATWG HTML Standard",
      year: "Living standard",
      url: "https://html.spec.whatwg.org/multipage/server-sent-events.html",
      relevance: "The official rules for event-stream framing, parsing, IDs, reconnection, and UTF-8 behavior.",
    },
    {
      role: "Specification",
      title: "Streams Standard",
      authors: "WHATWG",
      year: "Living standard",
      url: "https://streams.spec.whatwg.org/",
      relevance: "Defines how readable streams, readers, queues, cancellation, and backpressure work.",
    },
    {
      role: "Guide",
      title: "Using server-sent events",
      authors: "MDN Web Docs",
      year: "Current",
      url: "https://developer.mozilla.org/en-US/docs/Web/API/Server-sent_events/Using_server-sent_events",
      relevance: "Gives practical browser and server examples for event names, data fields, errors, and connection limits.",
    },
  ],
  "scheduling-memory": [
    {
      role: "Primary",
      title: "Orca: A Distributed Serving System for Transformer-Based Generative Models",
      authors: "Gyeong-In Yu et al.",
      year: "2022",
      url: "https://www.usenix.org/conference/osdi22/presentation/yu",
      relevance: "Introduces iteration-level scheduling and selective batching for autoregressive model serving.",
    },
    {
      role: "Paper",
      title: "PagedAttention and vLLM",
      authors: "Woosuk Kwon et al.",
      year: "2023",
      url: "https://arxiv.org/abs/2309.06180",
      relevance: "Shows how memory allocation and continuous batching affect each other when requests have different lengths.",
    },
    {
      role: "Paper",
      title: "Taming Throughput-Latency Tradeoff with Sarathi-Serve",
      authors: "Amey Agrawal et al.",
      year: "2024",
      url: "https://arxiv.org/abs/2403.02310",
      relevance: "Uses chunked prefills and stall-free schedules to balance throughput against token latency.",
    },
  ],
  "reliability-observability": [
    {
      role: "Primary",
      title: "Monitoring Distributed Systems",
      authors: "Google SRE",
      year: "2016",
      url: "https://sre.google/sre-book/monitoring-distributed-systems/",
      relevance: "Explains why latency, traffic, errors, and saturation are the monitoring signals that matter most.",
    },
    {
      role: "Guide",
      title: "Alerting on SLOs",
      authors: "Google SRE Workbook",
      year: "2018",
      url: "https://sre.google/workbook/alerting-on-slos/",
      relevance: "Shows how to turn error budgets and burn rates into alerts people can act on.",
    },
    {
      role: "Specification",
      title: "OpenTelemetry Trace specification",
      authors: "OpenTelemetry",
      year: "Current",
      url: "https://opentelemetry.io/docs/specs/otel/trace/",
      relevance: "Defines spans, context, events, status, sampling, and export rules for distributed traces.",
    },
  ],
  "conversation-state": [
    {
      role: "Primary",
      title: "Extracting State Logic into a Reducer",
      authors: "React",
      year: "Current",
      url: "https://react.dev/learn/extracting-state-logic-into-a-reducer",
      relevance: "Shows how pure reducers and actions keep complicated UI state changes manageable.",
    },
    {
      role: "Guide",
      title: "Choosing the State Structure",
      authors: "React",
      year: "Current",
      url: "https://react.dev/learn/choosing-the-state-structure",
      relevance: "Covers normalized data, derived state, avoiding contradictions, and using stable IDs.",
    },
    {
      role: "Guide",
      title: "Preserving and Resetting State",
      authors: "React",
      year: "Current",
      url: "https://react.dev/learn/preserving-and-resetting-state",
      relevance: "Explains how component identity and keys decide whether chat state survives a render.",
    },
  ],
  "streaming-react": [
    {
      role: "Primary",
      title: "Using readable streams",
      authors: "MDN Web Docs",
      year: "Current",
      url: "https://developer.mozilla.org/en-US/docs/Web/API/Streams_API/Using_readable_streams",
      relevance: "Shows how to read, cancel, and build asynchronous streams in the browser.",
    },
    {
      role: "Specification",
      title: "Streams Standard",
      authors: "WHATWG",
      year: "Living standard",
      url: "https://streams.spec.whatwg.org/",
      relevance: "The official rules for chunks, readers, queues, cancellation, and backpressure.",
    },
    {
      role: "Guide",
      title: "useTransition",
      authors: "React",
      year: "Current",
      url: "https://react.dev/reference/react/useTransition",
      relevance: "Explains how non-blocking renders can keep the UI responsive during frequent updates.",
    },
  ],
  "chat-actions-context": [
    {
      role: "Primary",
      title: "Conversation state",
      authors: "OpenAI API documentation",
      year: "Current",
      url: "https://developers.openai.com/api/docs/guides/conversation-state",
      relevance: "Explains how to carry a conversation across separate model requests.",
    },
    {
      role: "Guide",
      title: "AbortController",
      authors: "MDN Web Docs",
      year: "Current",
      url: "https://developer.mozilla.org/en-US/docs/Web/API/AbortController",
      relevance: "Covers the browser API used to stop fetches, streams, and generation work.",
    },
    {
      role: "Guide",
      title: "Queueing a Series of State Updates",
      authors: "React",
      year: "Current",
      url: "https://react.dev/learn/queueing-a-series-of-state-updates",
      relevance: "Explains the queued state updates behind retry, edit, and streaming actions.",
    },
  ],
  "chat-product-quality": [
    {
      role: "Primary",
      title: "ARIA23: Using role=log to identify sequential information updates",
      authors: "W3C Web Accessibility Initiative",
      year: "WCAG 2.2",
      url: "https://www.w3.org/WAI/WCAG22/Techniques/aria/ARIA23",
      relevance: "Explains how role=log identifies new items, like messages added to a conversation.",
    },
    {
      role: "Specification",
      title: "Understanding Status Messages",
      authors: "W3C Web Accessibility Initiative",
      year: "WCAG 2.2",
      url: "https://www.w3.org/WAI/WCAG22/Understanding/status-messages",
      relevance: "Explains when assistive technology needs to announce progress, completion, and errors.",
    },
    {
      role: "Guide",
      title: "Interaction to Next Paint",
      authors: "web.dev",
      year: "Current",
      url: "https://web.dev/articles/inp",
      relevance: "Provides a practical way to measure interaction and streaming-render responsiveness.",
    },
  ],
};

export function getLessonSources(lessonId: string) {
  const sources = lessonSources[lessonId];
  if (!sources || sources.length < 2) throw new Error(`Lesson ${lessonId} requires multiple sources.`);
  return sources;
}
